### ISSUE TITLE
Corrupt transcoded video with rkmpp decoder.

### ISSUE THREAD

**Issue by kaaku3** [immich-app/immich#13709]
### The bug

X265 4K videos, transcoded down to 720p x265 using rkmmp hardware accelerated encoding and decoding are sometimes corrupted causing looped playback and strange colours and artifacts when played back.
Video seem fine with HW decoding disabled.
It does not happen every time and is inconsistent but happens often.

### The OS that Immich Server is running on

Armbian Bookworm 

### Version of Immich Server

V1.118.2

### Version of Immich Mobile App

V1.118.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Same as default
```

### Your .env content

```Shell
Same as default
```

### Reproduction steps

1.
2.
3.
...

**Comment by kaaku3** [comment]
Hi, Are you sure this is fixed?
You mentioned in #13785 that HW decoding is untested.
The problem I reported only affects HW decoding.

**Comment by mertalev** [comment]
I tested this separately and I think it's caused by [this](https://github.com/jellyfin/jellyfin-ffmpeg/issues/482) issue. You're most likely seeing tone-mapping artifacts that will be fixed by setting the peak luminance explicitly.

**Comment by kaaku3** [comment]
Thankyou very much for getting back to me, I appreciate all the hard work.

**Comment by kaaku3** [comment]
HI, Unfortunately I did still have the same problem on hardware decoded transcoded videos in v1.120.
It has significantly improved but is still happening in low light videos

**Comment by mertalev** [comment]
Hmm, I guess peak=100 (1000 nits) is too high for dark vidoes. Can you share the output of `mediainfo <path>` or `ffprobe -show_streams <path>` for an affected video? Maybe we can use a different number based on certain metadata.

**Comment by mertalev** [comment]
Also, are the videos experiencing issues in 1.120.0 the same videos that looked corrupt in earlier versions? Or do different videos look corrupt now?

**Comment by kaaku3** [comment]
I just did transcoding on all after the updated HDR tone mapping.
I noticed that videos that were corrupted before in bright scenes are now fine, but more recent videos taken in a dark concert were corrupted. I then  took ok a video a dark room at night and it too was corrupted.
Currently transcoding is still running with hardware acceleration for decode off.
My library takes a few hours to transcode with hardware decode and encode, a day or so for encode only, and many many weeks for software only.

I'm happy to rerun the job on single files once the transcode job completes, but I don't know much about 
linux other than what is in the immich docker install guide.
If there is a guide of a way to provide better logs, I'm happy to follow instructions.

**Comment by kaaku3** [comment]
Media Info

General
Complete name                            : PXL_20241105_062315977.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/mp41)
File size                                : 54.8 MiB
Duration                                 : 7 s 250 ms
Overall bit rate                         : 63.4 Mb/s
Frame rate                               : 59.859 FPS
Encoded date                             : 2024-11-05 06:23:25 UTC
Tagged date                              : 2024-11-05 06:23:25 UTC
xyz                                      : +35.6247+139.4298/
com.android.manufacturer                 : Google
com.android.model                        : Pixel 6a

Video
ID                                       : 3
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main@L5.1@High
Codec ID                                 : hvc1
Codec ID/Info                            : High Efficiency Video Coding
Duration                                 : 7 s 250 ms
Bit rate                                 : 63.1 Mb/s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Rotation                                 : 90°
Frame rate mode                          : Variable
Frame rate                               : 59.859 FPS
Minimum frame rate                       : 59.367 FPS
Maximum frame rate                       : 60.362 FPS
Real frame rate                          : 60.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Bits/(Pixel*Frame)                       : 0.127
Stream size                              : 54.5 MiB (100%)
Title                                    : VideoHandle
Language                                 : English
Encoded date                             : 2024-11-05 06:23:25 UTC
Tagged date                              : 2024-11-05 06:23:25 UTC
Color range                              : Full
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
Codec configuration box                  : hvcC

Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 7 s 243 ms
Bit rate mode                            : Constant
Bit rate                                 : 192 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 170 KiB (0%)
Title                                    : SoundHandle
Language                                 : English
Encoded date                             : 2024-11-05 06:23:25 UTC
Tagged date                              : 2024-11-05 06:23:25 UTC

Other
Type                                     : meta
Duration                                 : 7 s 250 ms
Bit rate mode                            : Variable

**Comment by mertalev** [comment]
Hmm, it doesn't seem like this is an HDR video. Could you follow these steps:

1. Change immich's log level to debug  in the admin settings under Log Settings
2. Run transcoding for this asset
3. In the terminal, run `docker logs immich_server`
4. Find the latest log that shows an `ffmpeg` command (has `/usr/bin/ffmpeg` in it)

I'm curious to see what the specific command is to see where this is going wrong.

**Comment by kaaku3** [comment]
I set log level to debug, but unfortunately i do not see ffmpeg anything.
Only thing I see that is remotely related in the log is:
[Nest] 17  - 11/09/2024, 1:18:31 PM VERBOSE [Api:LoggingInterceptor~p0aolibi] {"assetIds":[],"name":"transcode-video"}

**Comment by kaaku3** [comment]
Disregard that, the problem was the option "refresh encoded videos" is not re-encoding the video... maybe i misunderstood the meaning of that feature.

I made a new video in low light and uploaded it with hardware decoding on, the result was corruption towards the end of the file.

ffmpeg -n 10 /usr/bin/ffmpeg -hwaccel rkmpp -hwaccel_output_format drm_prime -afbc rga -noautorotate -i upload/library/Kirk/2024/2024-11-09/PXL_20241109_133516985.mp4 -y -c:v hevc_rkmpp -c:a aac -movflags faststart -fps_mode passthrough -map 0:2 -map 0:1 -g 256 -tag:v hvc1 -v verbose -vf scale_rkrga=720:-2:format=nv12:afbc=1 -level 153 -rc_mode CQP -qp_init 28 upload/encoded-video/c160480f-610d-42d9-8cea-829489f5a58e/f2/b0/f2b017d0-38f9-4331-8f71-d7c71e48b0c2.mp4

I then renamed the file and reuploaded it with hardware decoding off and the resulting file was fine.

ffmpeg -n 10 /usr/bin/ffmpeg -i upload/library/Kirk/2024/2024-11-09/reupload.mp4 -y -c:v hevc_rkmpp -c:a aac -movflags faststart -fps_mode passthrough -map 0:2 -map 0:1 -g 256 -tag:v hvc1 -v verbose -vf scale=720:-2 -level 153 -rc_mode CQP -qp_init 28 upload/encoded-video/c160480f-610d-42d9-8cea-829489f5a58e/8d/4e/8d4e5afc-9692-4169-b813-67ba68b96fdd.mp4

Media info for file

General
Complete name                            : Kirk/2024/2024-11-09/reupload.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/mp41)
File size                                : 78.3 MiB
Duration                                 : 10 s 515 ms
Overall bit rate                         : 62.5 Mb/s
Frame rate                               : 59.536 FPS
Movie name                               : Re-upload
Encoded date                             : 2024-11-09 13:35:28 UTC
Tagged date                              : 2024-11-09 13:35:28 UTC
xyz                                      : +35.6879+139.4576/
com.android.model                        : Pixel 7a
com.android.manufacturer                 : Google

Video
ID                                       : 3
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main@L6@Main
Codec ID                                 : hvc1
Codec ID/Info                            : High Efficiency Video Coding
Duration                                 : 10 s 515 ms
Bit rate                                 : 62.2 Mb/s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Rotation                                 : 90°
Frame rate mode                          : Variable
Frame rate                               : 59.536 FPS
Minimum frame rate                       : 42.959 FPS
Maximum frame rate                       : 96.774 FPS
Real frame rate                          : 60.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Bits/(Pixel*Frame)                       : 0.126
Stream size                              : 78.0 MiB (100%)
Language                                 : English
Encoded date                             : 2024-11-09 13:35:28 UTC
Tagged date                              : 2024-11-09 13:35:28 UTC
Color range                              : Full
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
Codec configuration box                  : hvcC

Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 10 s 505 ms
Bit rate mode                            : Constant
Bit rate                                 : 192 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 246 KiB (0%)
Language                                 : English
Encoded date                             : 2024-11-09 13:35:28 UTC
Tagged date                              : 2024-11-09 13:35:28 UTC

Other
Type                                     : meta
Duration                                 : 10 s 515 ms
Bit rate mode                            : Variable

I think you are right they are not HDR, but with the latest update corruption only seems to happen in low light videos, where as before the update it seemed more random.

**Comment by mertalev** [comment]
In the transcoding settings under Advanced, could you set the keyframe interval to 60? I wonder if that has an effect here.

**Comment by kaaku3** [comment]
Wow yes, its seems fine with "Maximum keyframe interval" set to 60, thank you so much.
Is it bad to keep it at 60 as opposed to auto?

**Comment by mertalev** [comment]
It will make the videos very slightly bigger, but otherwise no downside as far as I know.

**Comment by kaaku3** [comment]
Ok, thankyou.
keeping the file size down was the reason i'm transcoding at all, as my mobile data plan is slow sometimes.

Not sure if it's related but i just noticed a very very thin line at the top and bottom of the video that is not there when I use software decoding.

**Comment by mertalev** [comment]
The default in your case is 256, for reference. Can you try setting it to, say, 120? I'm thinking of changing the default for RKMPP to remedy this, but also trying to minimize the impact to file size.

**Comment by mertalev** [comment]
cc @nyanmisaka if you have any insight into what's causing this behavior

**Comment by kaaku3** [comment]
After deleting and re-uploading the same to files one a dark video and one bright.
with 60 still sometimes is causing an issue on both bright and dark video.
128 was very bad.
Haven't seen a problem with it set to 32 after a few uploads.
The line I mentioned only affects hardware decoded videos and only visible on the android mobile app, not on web.

**Comment by kaaku3** [comment]
Since software decode is working fine with rkmpp hardware encode on its defaults, is there not any settings to play with on the hardware decode side?
Just after some googling it seems not everyone is getting perfect results with ffmpeg and drm_prime, could that be the problem?
The hardware decoder or ffmpegs compatibility with drm_prime? I don't really understand any of this but is there an alternative to drm_prime with rkmpp?

**Comment by mertalev** [comment]
A max of 32 for a 60 FPS video is a keyframe roughly every 0.5s. This is okay, but I think it's the lowest that's reasonable to use.

What's particularly weird is that this is an encoding setting - it shouldn't be fixed by using software decoding. It's a combination of the frames being outputted by hardware decoding and the keyframe interval that's causing this issue.

I think drm_prime is needed for good performance so filters can directly access the frames in the GPU without copying them.

**Comment by kaaku3** [comment]
I'd like to help in anyway I can but I'm not very knowledgeable but i can follow instructions, do any of the devs have access to an rkmpp device?

**Comment by kaaku3** [comment]
I hope it doesn't seem like i'm complaining about the issue too much, I understand you must be busy on other things.
I love immich and i'm just grateful that rkmpp encode works at all, otherwise i'd have to buy a more power hungry device.

**Comment by nyanmisaka** [comment]
What’s the SoC model and rockchip linux kernel version? (uname -a) 

Can u share a sample clip and the full ffmpeg command line?

I may have time to take a look tomorrow.

**Comment by mertalev** [comment]
No worries! It's great that you're reporting on this so we know about it and can fix it.

I think the best option would be to open an issue in jellyfin-ffmpeg as I believe most/all of the RKMPP decoders, filters and encoders are implemented by them. A zipped sample video would be particularly helpful.

**Comment by mertalev** [comment]
According to OP, this command is problematic:
```
ffmpeg -hwaccel rkmpp -hwaccel_output_format drm_prime -afbc rga -noautorotate -i upload/library/Kirk/2024/2024-11-09/PXL_20241109_133516985.mp4 -y -c:v hevc_rkmpp -c:a aac -movflags faststart -fps_mode passthrough -map 0:2 -map 0:1 -g 256 -tag:v hvc1 -v verbose -vf scale_rkrga=720:-2:format=nv12:afbc=1 -level 153 -rc_mode CQP -qp_init 28 upload/encoded-video/c160480f-610d-42d9-8cea-829489f5a58e/f2/b0/f2b017d0-38f9-4331-8f71-d7c71e48b0c2.mp4
```

This command works fine:
```
ffmpeg -i upload/library/Kirk/2024/2024-11-09/reupload.mp4 -y -c:v hevc_rkmpp -c:a aac -movflags faststart -fps_mode passthrough -map 0:2 -map 0:1 -g 256 -tag:v hvc1 -v verbose -vf scale=720:-2 -level 153 -rc_mode CQP -qp_init 28 upload/encoded-video/c160480f-610d-42d9-8cea-829489f5a58e/8d/4e/8d4e5afc-9692-4169-b813-67ba68b96fdd.mp4
```

And changing the first command to use `-g 32` instead of `-g 256` also works fine.

**Comment by kaaku3** [comment]
uname -a
Linux immich-server 5.10.160-legacy-rk35xx #1 SMP Wed May 15 03:04:45 UTC 2024 aarch64 GNU/Linux
Its actually a rk3588s.
This is my sample video of a messy (excuse the mess) dark room that constantly causes issues.
2 files one with -g256 and one with -g 32.
In this instance -g 32 is also corrupt (up to this point -g32 was actually fine)
It seems hit or miss.
https://mde.mydns.jp/share/K43Bd1reYFwON1RolUloygNxsFHhvFXPcoRfaQB4AFFohEqEjqLAF4on16gn819xOD4

Thankyou for the command line noted above and the description is perfect, the line thing happens no matter the -g setting and  is only visible in mobile app (android) maybe web viewer clips it off?

**Comment by w00tlarr** [comment]
Hiya - running into this issue too but with Intel iGPU hardware acceleration. No issues encoding without iGPU.

**Comment by w00tlarr** [comment]
Sample video after Intel iGPU hardware transcode using VAAPI or QuickSync.

https://github.com/user-attachments/assets/2c0df285-4d35-440c-94cf-ba0dae5469d1

**Comment by kaaku3** [comment]
Great to hear a fix is on the way, thankyou so much.

**Comment by kaaku3** [comment]
So the reason it didn't happen with software decode was because it was because it was slower?

**Comment by nyanmisaka** [comment]
> Sample video after Intel iGPU hardware transcode using VAAPI or QuickSync.
> 
>  playback.mp4

This is a completely different issue. Due to the driver/kernel rather than FFmpeg.

https://github.com/intel/media-driver/issues/1665

**Comment by nyanmisaka** [comment]
> Great to hear a fix is on the way, thankyou so much. (I was beginning to wonder if my chip was faulty)

The version in the link above should fix this artifact. You can try to install it manually and try again.

As for the green line I couldn't reproduce it in Chrome, PotPlayer, MPC-BE and even FFplay. So it is a problem specific to the built-in video player of your client platform.

720x406 hevc main
![720x406](https://github.com/user-attachments/assets/f5ffe03c-5e12-4bb9-a5d4-2e7cdb987908)

**Comment by kaaku3** [comment]
Thankyou, I'm not nearly versed enough with docker to update ffmpeg from source,I will wait for this to reach immich in an update.
The line, I was only about to reproduce in the immich app and only with files hardware decided and encoded.

You can see it here top left, and bottom middle in this screenshot
![Screenshot_20241111-175451](https://github.com/user-attachments/assets/36069bd0-197b-4300-b43e-03124d416c6f)

**Comment by nyanmisaka** [comment]
> Thankyou, I'm not nearly versed enough with docker to update ffmpeg from source,I will wait for this to reach immich in an update. The line, I was only about to reproduce in the immich app and only with files hardware decided and encoded.
> 
> You can see it here top left, and bottom middle in this screenshot

It's best to switch to a different client and try again.

**Comment by nyanmisaka** [comment]
For example, I cannot reproduce it on iPhone/iOS 17.

![IMG_8534](https://github.com/user-attachments/assets/e6230fc3-ecd3-4e1c-ad03-0ff264442c19)

**Comment by kaaku3** [comment]
Ok, I will try it with the updated immich client, once the fix reaches it maybe it's not an issue anymore.
If it's still an issue I will open up an issue with the immich mobile app for android.

**Comment by w00tlarr** [comment]
> > Sample video after Intel iGPU hardware transcode using VAAPI or QuickSync.
> > playback.mp4
> 
> This is a completely different issue. Due to the driver/kernel rather than FFmpeg.
> 
> [intel/media-driver#1665](https://github.com/intel/media-driver/issues/1665)

Thanks. Yeah it's that bug with the Intel Media Driver link you provided. Not sure if I should open a separate bug now as it seems to be a very very old issue with Proxmox + SRIOV + my new iPhone 16 with HDR videos. I just noticed this issue because of my new iPhone is recording HDR videos vs. my old iPhone XR.

Disabling the Tone-Mapping in the Immich Video Transcoding setting now works properly with hardware acceleration.

Anyways, I can open a new bug thread for tips to other folks, if needed.

**Comment by nyanmisaka** [comment]
> > > Sample video after Intel iGPU hardware transcode using VAAPI or QuickSync.
> > > playback.mp4
> > 
> > 
> > This is a completely different issue. Due to the driver/kernel rather than FFmpeg.
> > [intel/media-driver#1665](https://github.com/intel/media-driver/issues/1665)
> 
> Thanks. Yeah it's that bug with the Intel Media Driver link you provided. Not sure if I should open a separate bug now as it seems to be a very very old issue with Proxmox + SRIOV + my new iPhone 16 with HDR videos. I just noticed this issue because of my new iPhone is recording HDR videos vs. my old iPhone XR.
> 
> Disabling the Tone-Mapping in the Immich Video Transcoding setting now works properly with hardware acceleration.
> 
> Anyways, sorry for hijacking this thread as it read like the same issue with me. I can open a new bug thread for tips to other folks, if needed.

I don't have an Intel GPU that supports SRIOV at the moment (Intel ARC A380), you could try looking in the Intel repo to provide some context. But anyway this issue is not related to the downstream software, as the same FFmpeg commands run perfectly on the host.

**Comment by mertalev** [comment]
@kaaku3 The bug fix for the RKMPP issue should be in 1.120.2. Can you try with that?

**Comment by kaaku3** [comment]
@mertalev that's great news, unfortunately my armbian server that immich was running went down last night.
I didn't touch anything, I don't know why. 
You think publicly putting out a link to a video on immich was a bad idea?
I'm sure people have better things to do then mess with my server probably over thinking it.
Anyway I think I will need to put the immich backup restore feature to use today.
I will let you know if it's fixed as soon as i can.
Thankyou fire your help.

**Comment by mertalev** [comment]
Sorry to hear that! There are lots of reasons it could fail, like power loss. But in general, make sure the server is hardened with a reverse proxy, fail2ban, etc. if you're exposing it to the internet. Definitely don't expose Immich (or any other service) directly.

**Comment by kaaku3** [comment]
I was using nginx, I will look into fail2ban too thankyou.

**Comment by kaaku3** [comment]
Hi, I started fresh. I had a lot of problems seems the newer kernel don't fully support hardware acceleration... i'm not quite sure.
I went with Joshua Rieks ubuntu with legacy kernel, that apparent everything should work out of the box, but i had problems with opencl. It seems to be working now, but I'm not 100%. Is there anyway from immich log to tell if its falling back to software encode. It doesn't seem to be going as fast as it was before. Also immich restore didn't work for me so i'm uploading everything.

this is the ffmpeg from immich log

ffmpeg -n 10 /usr/bin/ffmpeg -hwaccel rkmpp -hwaccel_output_format drm_prime -afbc rga -noautorotate -i upload/upload/0175ee76-7502-46c4-9685-08b06e26c9dc/a7/f0/a7f09b0f-653d-4920-8a95-ec929b890cc8.mp4 -y -c:v hevc_rkmpp -c:a aac -movflags faststart -fps_mode passthrough -map 0:2 -map 0:1 -g 256 -tag:v hvc1 -v verbose -vf scale_rkrga=720:-2:format=nv12:afbc=1 -level 153 -rc_mode CQP -qp_init 28 upload/encoded-video/0175ee76-7502-46c4-9685-08b06e26c9dc/f9/57/f9578312-e623-4a61-9667-607baed5a02e.mp4

anyway to tell from that that it isn't falling back to software?
I'm currently waiting on the problem file to be transcoded.

**Comment by mertalev** [comment]
It seems like this is the relevant line:
```
[hevc_rkmpp @ 0x3b53a2d0500] Failed to get key input frame from packet meta: -1
```
Does it fail for all videos, or only certain ones?

**Comment by kaaku3** [comment]
Thankyou for pointing that out,it seems to be only one file.
I was starting to think something was up with the drivers.
Looks as tho it was uploaded via an  immich client on my wife's phone, is it possible it was something up with the upload...
It fell back to software transcode and passed that ok

**Comment by mertalev** [comment]
Thanks for clarifying. I'm assuming the corruption issue is resolved now?

I'm not sure what the issue is for that particular video, but if it worked with software decoding then it's most likely a bug.

**Comment by mertalev** [comment]
[ubuntu-rockchip](https://github.com/Joshua-Riek/ubuntu-rockchip) tends to be recommended as the best for hardware acceleration support.

**Comment by kaaku3** [comment]
Ok, thankyou

**Comment by mertalev** [comment]
You can also try downgrading back to 1.120.1 to see if you still get the same error. That would make it clear whether the issue is due to the different server environment or the FFmpeg change.

**Comment by kaaku3** [comment]
I just wiped it ;), I'll keep that in mind if it persists

**Comment by kaaku3** [comment]
Sorry to keeps bothering you here... I think the base system is fine now, but in immich when i run transcoding despite having hardware decoding enable... I don't think it is.
here is the ffmepg output
ffmpeg -n 10 /usr/bin/ffmpeg -i upload/library/admin/2020/2020-10-24/PXL_20201024_021840973.mp4 -y -c:v hevc_rkmpp -c:a aac -movflags faststart -fps_mode passthrough -map 0:1 -map 0:0 -g 256 -tag:v hvc1 -v verbose -vf scale=-2:720 -level 153 -rc_mode CQP -qp_init 28 upload/encoded-video/a32baa7e-7326-459b-a8ab-f08034213bb7/14/de/14de9676-c1c3-4e73-80e8-e3b614773b6d.mp4

**Comment by mertalev** [comment]
Yes, the issue is the lack of OpenCL. There's a PR to loosen this restriction so it tries to still use hardware decoding and only do tone-mapping on CPU (if it's an HDR video).

The `Failed to get key input frame from packet meta: -1` error you mentioned should be fixed in the next release.

**Comment by kaaku3** [comment]
Thankyou, yeah I was keeping an eye on jellyfin ffmpeg and I hoped that's what that commit meant.

I think something is wrong with my base system now..
I just can't figure out out.

arm_release_ver: g13p0-01eac0, rk_so_ver: 3
Failed creating base context during opening of kernel driver.
Kernel module may not have been loaded
Number of platforms                               2
  Platform Name                                   ARM Platform
  Platform Vendor                                 ARM
  Platform Version                                OpenCL 3.0 v1.g13p0-01eac0.a8b6f0c7e1f83c654c60d1775112dbe4
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_3d_image_writes cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_fp16 cl_khr_icd cl_khr_egl_image cl_khr_image2d_from_buffer cl_khr_depth_images cl_khr_subgroups cl_khr_subgroup_extended_types cl_khr_subgroup_non_uniform_vote cl_khr_subgroup_ballot cl_khr_subgroup_non_uniform_arithmetic cl_khr_subgroup_shuffle cl_khr_subgroup_shuffle_relative cl_khr_subgroup_clustered_reduce cl_khr_subgroup_rotate cl_khr_il_program cl_khr_priority_hints cl_khr_create_command_queue cl_khr_spirv_no_integer_wrap_decoration cl_khr_extended_versioning cl_khr_device_uuid cl_khr_suggested_local_work_size cl_khr_extended_bit_ops cl_khr_integer_dot_product cl_khr_semaphore cl_khr_external_semaphore cl_khr_external_semaphore_sync_fd cl_khr_command_buffer cl_arm_core_id cl_arm_printf cl_arm_non_uniform_work_group_size cl_arm_import_memory cl_arm_import_memory_dma_buf cl_arm_import_memory_host cl_arm_integer_dot_product_int8 cl_arm_integer_dot_product_accumulate_int8 cl_arm_integer_dot_product_accumulate_saturate_int8 cl_arm_scheduling_controls cl_arm_controlled_kernel_termination cl_ext_cxx_for_opencl cl_ext_image_tiling_control cl_ext_image_requirements_info cl_ext_image_from_buffer
  Platform Extensions with Version                cl_khr_global_int32_base_atomics                                 0x400000 (1.0.0)
                                                  cl_khr_global_int32_extended_atomics                             0x400000 (1.0.0)
                                                  cl_khr_local_int32_base_atomics                                  0x400000 (1.0.0)
                                                  cl_khr_local_int32_extended_atomics                              0x400000 (1.0.0)
                                                  cl_khr_byte_addressable_store                                    0x400000 (1.0.0)
                                                  cl_khr_3d_image_writes                                           0x400000 (1.0.0)
                                                  cl_khr_int64_base_atomics                                        0x400000 (1.0.0)
                                                  cl_khr_int64_extended_atomics                                    0x400000 (1.0.0)
                                                  cl_khr_fp16                                                      0x400000 (1.0.0)
                                                  cl_khr_icd                                                       0x400000 (1.0.0)
                                                  cl_khr_egl_image                                                 0x400000 (1.0.0)
                                                  cl_khr_image2d_from_buffer                                       0x400000 (1.0.0)
                                                  cl_khr_depth_images                                              0x400000 (1.0.0)
                                                  cl_khr_subgroups                                                 0x400000 (1.0.0)
                                                  cl_khr_subgroup_extended_types                                   0x400000 (1.0.0)
                                                  cl_khr_subgroup_non_uniform_vote                                 0x400000 (1.0.0)
                                                  cl_khr_subgroup_ballot                                           0x400000 (1.0.0)
                                                  cl_khr_subgroup_non_uniform_arithmetic                           0x400000 (1.0.0)
                                                  cl_khr_subgroup_shuffle                                          0x400000 (1.0.0)
                                                  cl_khr_subgroup_shuffle_relative                                 0x400000 (1.0.0)
                                                  cl_khr_subgroup_clustered_reduce                                 0x400000 (1.0.0)
                                                  cl_khr_subgroup_rotate                                           0x400000 (1.0.0)
                                                  cl_khr_il_program                                                0x400000 (1.0.0)
                                                  cl_khr_priority_hints                                            0x400000 (1.0.0)
                                                  cl_khr_create_command_queue                                      0x400000 (1.0.0)
                                                  cl_khr_spirv_no_integer_wrap_decoration                          0x400000 (1.0.0)
                                                  cl_khr_extended_versioning                                       0x400000 (1.0.0)
                                                  cl_khr_device_uuid                                               0x400000 (1.0.0)
                                                  cl_khr_suggested_local_work_size                                 0x400000 (1.0.0)
                                                  cl_khr_extended_bit_ops                                          0x400000 (1.0.0)
                                                  cl_khr_integer_dot_product                                       0x800000 (2.0.0)
                                                  cl_khr_semaphore                                                   0x9000 (0.9.0)
                                                  cl_khr_external_semaphore                                          0x9000 (0.9.0)
                                                  cl_khr_external_semaphore_sync_fd                                  0x9000 (0.9.0)
                                                  cl_khr_command_buffer                                              0x9000 (0.9.0)
                                                  cl_arm_core_id                                                   0x400000 (1.0.0)
                                                  cl_arm_printf                                                    0x400000 (1.0.0)
                                                  cl_arm_non_uniform_work_group_size                               0x400000 (1.0.0)
                                                  cl_arm_import_memory                                             0x400000 (1.0.0)
                                                  cl_arm_import_memory_dma_buf                                     0x400000 (1.0.0)
                                                  cl_arm_import_memory_host                                        0x400000 (1.0.0)
                                                  cl_arm_integer_dot_product_int8                                  0x400000 (1.0.0)
                                                  cl_arm_integer_dot_product_accumulate_int8                       0x400000 (1.0.0)
                                                  cl_arm_integer_dot_product_accumulate_saturate_int8              0x400000 (1.0.0)
                                                  cl_arm_scheduling_controls                                         0x4000 (0.4.0)
                                                  cl_arm_controlled_kernel_termination                             0x400000 (1.0.0)
                                                  cl_ext_cxx_for_opencl                                            0x400000 (1.0.0)
                                                  cl_ext_image_tiling_control                                        0x1000 (0.1.0)
                                                  cl_ext_image_requirements_info                                     0x5000 (0.5.0)
                                                  cl_ext_image_from_buffer                                         0x400000 (1.0.0)
  Platform Numeric Version                        0xc00000 (3.0.0)
  Platform Extensions function suffix             ARM
  Platform Host timer resolution                  1ns
  Platform Semaphore types                        Binary
  Platform External semaphore import types        0
  Platform External semaphore export types        0

  Platform Name                                   ARM Platform
  Platform Vendor                                 ARM
  Platform Version                                OpenCL 3.0 v1.g13p0-01eac0.a8b6f0c7e1f83c654c60d1775112dbe4
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_3d_image_writes cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_fp16 cl_khr_icd cl_khr_egl_image cl_khr_image2d_from_buffer cl_khr_depth_images cl_khr_subgroups cl_khr_subgroup_extended_types cl_khr_subgroup_non_uniform_vote cl_khr_subgroup_ballot cl_khr_subgroup_non_uniform_arithmetic cl_khr_subgroup_shuffle cl_khr_subgroup_shuffle_relative cl_khr_subgroup_clustered_reduce cl_khr_subgroup_rotate cl_khr_il_program cl_khr_priority_hints cl_khr_create_command_queue cl_khr_spirv_no_integer_wrap_decoration cl_khr_extended_versioning cl_khr_device_uuid cl_khr_suggested_local_work_size cl_khr_extended_bit_ops cl_khr_integer_dot_product cl_khr_semaphore cl_khr_external_semaphore cl_khr_external_semaphore_sync_fd cl_khr_command_buffer cl_arm_core_id cl_arm_printf cl_arm_non_uniform_work_group_size cl_arm_import_memory cl_arm_import_memory_dma_buf cl_arm_import_memory_host cl_arm_integer_dot_product_int8 cl_arm_integer_dot_product_accumulate_int8 cl_arm_integer_dot_product_accumulate_saturate_int8 cl_arm_scheduling_controls cl_arm_controlled_kernel_termination cl_ext_cxx_for_opencl cl_ext_image_tiling_control cl_ext_image_requirements_info cl_ext_image_from_buffer
  Platform Extensions with Version                cl_khr_global_int32_base_atomics                                 0x400000 (1.0.0)
                                                  cl_khr_global_int32_extended_atomics                             0x400000 (1.0.0)
                                                  cl_khr_local_int32_base_atomics                                  0x400000 (1.0.0)
                                                  cl_khr_local_int32_extended_atomics                              0x400000 (1.0.0)
                                                  cl_khr_byte_addressable_store                                    0x400000 (1.0.0)
                                                  cl_khr_3d_image_writes                                           0x400000 (1.0.0)
                                                  cl_khr_int64_base_atomics                                        0x400000 (1.0.0)
                                                  cl_khr_int64_extended_atomics                                    0x400000 (1.0.0)
                                                  cl_khr_fp16                                                      0x400000 (1.0.0)
                                                  cl_khr_icd                                                       0x400000 (1.0.0)
                                                  cl_khr_egl_image                                                 0x400000 (1.0.0)
                                                  cl_khr_image2d_from_buffer                                       0x400000 (1.0.0)
                                                  cl_khr_depth_images                                              0x400000 (1.0.0)
                                                  cl_khr_subgroups                                                 0x400000 (1.0.0)
                                                  cl_khr_subgroup_extended_types                                   0x400000 (1.0.0)
                                                  cl_khr_subgroup_non_uniform_vote                                 0x400000 (1.0.0)
                                                  cl_khr_subgroup_ballot                                           0x400000 (1.0.0)
                                                  cl_khr_subgroup_non_uniform_arithmetic                           0x400000 (1.0.0)
                                                  cl_khr_subgroup_shuffle                                          0x400000 (1.0.0)
                                                  cl_khr_subgroup_shuffle_relative                                 0x400000 (1.0.0)
                                                  cl_khr_subgroup_clustered_reduce                                 0x400000 (1.0.0)
                                                  cl_khr_subgroup_rotate                                           0x400000 (1.0.0)
                                                  cl_khr_il_program                                                0x400000 (1.0.0)
                                                  cl_khr_priority_hints                                            0x400000 (1.0.0)
                                                  cl_khr_create_command_queue                                      0x400000 (1.0.0)
                                                  cl_khr_spirv_no_integer_wrap_decoration                          0x400000 (1.0.0)
                                                  cl_khr_extended_versioning                                       0x400000 (1.0.0)
                                                  cl_khr_device_uuid                                               0x400000 (1.0.0)
                                                  cl_khr_suggested_local_work_size                                 0x400000 (1.0.0)
                                                  cl_khr_extended_bit_ops                                          0x400000 (1.0.0)
                                                  cl_khr_integer_dot_product                                       0x800000 (2.0.0)
                                                  cl_khr_semaphore                                                   0x9000 (0.9.0)
                                                  cl_khr_external_semaphore                                          0x9000 (0.9.0)
                                                  cl_khr_external_semaphore_sync_fd                                  0x9000 (0.9.0)
                                                  cl_khr_command_buffer                                              0x9000 (0.9.0)
                                                  cl_arm_core_id                                                   0x400000 (1.0.0)
                                                  cl_arm_printf                                                    0x400000 (1.0.0)
                                                  cl_arm_non_uniform_work_group_size                               0x400000 (1.0.0)
                                                  cl_arm_import_memory                                             0x400000 (1.0.0)
                                                  cl_arm_import_memory_dma_buf                                     0x400000 (1.0.0)
                                                  cl_arm_import_memory_host                                        0x400000 (1.0.0)
                                                  cl_arm_integer_dot_product_int8                                  0x400000 (1.0.0)
                                                  cl_arm_integer_dot_product_accumulate_int8                       0x400000 (1.0.0)
                                                  cl_arm_integer_dot_product_accumulate_saturate_int8              0x400000 (1.0.0)
                                                  cl_arm_scheduling_controls                                         0x4000 (0.4.0)
                                                  cl_arm_controlled_kernel_termination                             0x400000 (1.0.0)
                                                  cl_ext_cxx_for_opencl                                            0x400000 (1.0.0)
                                                  cl_ext_image_tiling_control                                        0x1000 (0.1.0)
                                                  cl_ext_image_requirements_info                                     0x5000 (0.5.0)
                                                  cl_ext_image_from_buffer                                         0x400000 (1.0.0)
  Platform Numeric Version                        0xc00000 (3.0.0)
  Platform Extensions function suffix             ARM
  Platform Host timer resolution                  1ns
  Platform Semaphore types                        Binary
  Platform External semaphore import types        0
  Platform External semaphore export types        0

  Platform Name                                   ARM Platform
Number of devices                                 1
arm_release_ver: g13p0-01eac0, rk_so_ver: 3
Failed creating base context during opening of kernel driver.
Kernel module may not have been loaded
  Device Name                                     <printDeviceInfo:0: get CL_DEVICE_NAME size : error -6>
  Device Vendor                                   ARM
arm_release_ver: g13p0-01eac0, rk_so_ver: 3
Failed creating base context during opening of kernel driver.
Kernel module may not have been loaded
  Device Vendor ID                                <printDeviceInfo:2: get CL_DEVICE_VENDOR_ID : error -6>
  Device Version                                  OpenCL 3.0 v1.g13p0-01eac0.a8b6f0c7e1f83c654c60d1775112dbe4
arm_release_ver: g13p0-01eac0, rk_so_ver: 3
Failed creating base context during opening of kernel driver.
Kernel module may not have been loaded
  Device UUID                                     <printDeviceInfo:6: get CL_DEVICE_UUID_KHR : error -6>
arm_release_ver: g13p0-01eac0, rk_so_ver: 3
Failed creating base context during opening of kernel driver.
Kernel module may not have been loaded
  Driver UUID                                     <printDeviceInfo:7: get CL_DRIVER_UUID_KHR : error -6>
arm_release_ver: g13p0-01eac0, rk_so_ver: 3
Failed creating base context during opening of kernel driver.
Kernel module may not have been loaded
  Valid Device LUID                               <printDeviceInfo:8: get CL_DEVICE_LUID_VALID_KHR : error -6>
arm_release_ver: g13p0-01eac0, rk_so_ver: 3
Failed creating base context during opening of kernel driver.
Kernel module may not have been loaded
  Device LUID                                     <printDeviceInfo:9: get CL_DEVICE_LUID_KHR : error -6>
arm_release_ver: g13p0-01eac0, rk_so_ver: 3
Failed creating base context during opening of kernel driver.
Kernel module may not have been loaded
  Device Node Mask                                <printDeviceInfo:10: get CL_DEVICE_NODE_MASK_KHR : error -6>
  Device Numeric Version                          0xc00000 (3.0.0)
  Driver Version                                  3.0
  Device OpenCL C Version                         OpenCL C 3.0 v1.g13p0-01eac0.a8b6f0c7e1f83c654c60d1775112dbe4
  Device OpenCL C Numeric Version                 0xc00000 (3.0.0)
  Device OpenCL C all versions                    OpenCL C                                                         0x400000 (1.0.0)
                                                  OpenCL C                                                         0x401000 (1.1.0)
                                                  OpenCL C                                                         0x402000 (1.2.0)
                                                  OpenCL C                                                         0x800000 (2.0.0)
                                                  OpenCL C                                                         0xc00000 (3.0.0)
  Device OpenCL C features                        __opencl_c_images                                                0x400000 (1.0.0)
                                                  __opencl_c_int64                                                 0x400000 (1.0.0)
                                                  __opencl_c_3d_image_writes                                       0x402000 (1.2.0)
                                                  __opencl_c_atomic_order_acq_rel                                  0x800000 (2.0.0)
                                                  __opencl_c_atomic_order_seq_cst                                  0x800000 (2.0.0)
                                                  __opencl_c_atomic_scope_device                                   0x800000 (2.0.0)
                                                  __opencl_c_atomic_scope_all_devices                              0x800000 (2.0.0)
                                                  __opencl_c_device_enqueue                                        0x800000 (2.0.0)
                                                  __opencl_c_generic_address_space                                 0x800000 (2.0.0)
                                                  __opencl_c_pipes                                                 0x800000 (2.0.0)
                                                  __opencl_c_program_scope_global_variables                        0x800000 (2.0.0)
                                                  __opencl_c_read_write_images                                     0x800000 (2.0.0)
                                                  __opencl_c_subgroups                                             0x800000 (2.0.0)
                                                  __opencl_c_work_group_collective_functions                       0x800000 (2.0.0)
  Device C++ for OpenCL Numeric Version           0x400000 (1.0.0)
  Latest conformance test passed                  v2021-03-05-00
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
arm_release_ver: g13p0-01eac0, rk_so_ver: 3
Failed creating base context during opening of kernel driver.
Kernel module may not have been loaded
  Max compute units                               <printDeviceInfo:32: get CL_DEVICE_MAX_COMPUTE_UNITS : error -6>
arm_release_ver: g13p0-01eac0, rk_so_ver: 3
Failed creating base context during opening of kernel driver.
Kernel module may not have been loaded
  Available core IDs (ARM)                        <printDeviceInfo:33: get CL_DEVICE_COMPUTE_UNITS_BITFIELD_ARM : error -6>
arm_release_ver: g13p0-01eac0, rk_so_ver: 3
Failed creating base context during opening of kernel driver.
Kernel module may not have been loaded
  Max clock frequency                             <printDeviceInfo:40: get CL_DEVICE_MAX_CLOCK_FREQUENCY : error -6>
  Device Partition                                (core)
    Max number of sub-devices                     0
    Supported partition types                     None
    Supported affinity domains                    (n/a)
  Max work item dimensions                        3
arm_release_ver: g13p0-01eac0, rk_so_ver: 3
Failed creating base context during opening of kernel driver.
Kernel module may not have been loaded
  Max work item sizes                             <printDeviceInfo:62: get number of CL_DEVICE_MAX_WORK_ITEM_SIZES : error -6>
arm_release_ver: g13p0-01eac0, rk_so_ver: 3
Failed creating base context during opening of kernel driver.
Kernel module may not have been loaded
  Max work group size                             <printDeviceInfo:63: get CL_DEVICE_MAX_WORK_GROUP_SIZE : error -6>
  Preferred work group size multiple (device)     16
Segmentation fault (core dumped)
ubuntu@ubuntu:~$ clinfo

**Comment by kaaku3** [comment]
Hi I just wanted to add that I still have the same
Failed to get key input frame from packet meta: -1 in the latest update.

**Comment by mertalev** [comment]
Unfortunately the fixed version was merged two hours after the release :/

Maybe we can do a patch release.

**Comment by kaaku3** [comment]
Good to hear the fix is still on the way. Thankyou

**Comment by mertalev** [comment]
Can you confirm if the issue is fully fixed now?

**Comment by kaaku3** [comment]
Hi, I'm currently away right now.
I clicked retranscose all in web interface and kept an eye on it via SSH on my phone. For some reason my system suspended... Maybe I pocket typed something... I'm not sure.
I was able to check that it  did about 4 thousand odd transcodes without error before it suspended though, so seems fixed.
Thankyou so much and thankyou for all the hard work.
I'm sorry I can't answer more definitely right now.

**Comment by mertalev** [comment]
Tentatively closing this issue since it sounds like it's fixed

**Comment by kaaku3** [comment]
I have rechecked my videos and I had absolutely no issues at all, including the line that appears in the video player, that appears fixed too.

Thankyou
