### ISSUE TITLE
Older iPhone 13 Pro Max Videos Still Cause Crashes and Aspect Ratio Issues After PR #12104

### ISSUE THREAD

**Issue by mosalski** [immich-app/immich#15407]
### The bug

Issue [#11689](https://github.com/immich-app/immich/issues/11689) was marked resolved by [PR #12104](https://github.com/immich-app/immich/pull/12104) in version v1.122.0, but older videos (uploaded before December 2024) are still problematic:

-   Older iPhone 13 Pro Max videos (uploaded around November 2024 and earlier) show up on Android (Samsung Galaxy S22 Ultra) with an incorrect aspect ratio.
-   Even older iPhone 13 Pro Max videos (uploaded before November 2024) cause the Immich app to crash on Android when opened.
-   On an iPhone 13 Pro Max, these older iPhone videos also sometimes show an incorrect aspect ratio, but do not crash the app.
-   Videos recorded on the Samsung Galaxy S22 Ultra do not have this issue at all.
-   Videos uploaded in December 2024 and throughout 2025 work correctly without any problems.

It appears the fix included in PR #12104 doesn’t apply retroactively to older uploads. Is there a way to reprocess or fix these videos so they work correctly?

### The OS that Immich Server is running on

Linux Mint 22

### Version of Immich Server

v1.124.2

### Version of Immich Mobile App

v1.124.0 build.173

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /media/vlad/Base/existing_pictures:/existing_pictures
      - /media/vlad/Base/photo:/media/vlad/Base/photo:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - model-cache:/cache
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
###################################################################################
# Database
###################################################################################

DB_HOSTNAME=immich_postgres
DB_USERNAME=im    
DB_PASSWORD=mich
DB_DATABASE_NAME=immich

# Optional Database settings:
# DB_PORT=5432

###################################################################################
# Redis
###################################################################################

REDIS_HOSTNAME=immich_redis

# Optional Redis settings:

# Note: these parameters are not automatically passed to the Redis Container
# to do so, please edit the docker-compose.yml file as well. Redis is not configured
# via environment variables, only redis.conf or the command line

# REDIS_PORT=6379
# REDIS_DBINDEX=0
# REDIS_PASSWORD=
# REDIS_SOCKET=

###################################################################################
# Upload File Location
#
# This is the location where uploaded files are stored.
###################################################################################

UPLOAD_LOCATION=/media/vlad/Base/immich


###################################################################################
# Typesense
###################################################################################
TYPESENSE_API_KEY=some-random-text
# TYPESENSE_ENABLED=false

###################################################################################
# Reverse Geocoding
#
# Reverse geocoding is done locally which has a small impact on memory usage
# This memory usage can be altered by changing the REVERSE_GEOCODING_PRECISION variable
# This ranges from 0-3 with 3 being the most precise
# 3 - Cities > 500 population: ~200MB RAM
# 2 - Cities > 1000 population: ~150MB RAM
# 1 - Cities > 5000 population: ~80MB RAM
# 0 - Cities > 15000 population: ~40MB RAM
####################################################################################

# DISABLE_REVERSE_GEOCODING=false
# REVERSE_GEOCODING_PRECISION=3

####################################################################################
# WEB - Optional
#
# Custom message on the login page, should be written in HTML form.
# For example:
# PUBLIC_LOGIN_PAGE_MESSAGE="This is a demo instance of Immich.<br><br>Email: <i>demo@demo.de</i><br>Password: <i>demo</i>"
####################################################################################

PUBLIC_LOGIN_PAGE_MESSAGE=

####################################################################################
# Alternative Service Addresses - Optional
#
# This is an advanced feature for users who may be running their immich services on different hosts.
# It will not change which address or port that services bind to within their containers, but it will change where other services look for their peers.
# Note: immich-microservices is bound to 3002, but no references are made
####################################################################################

IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003

####################################################################################
# Alternative API's External Address - Optional
#
# This is an advanced feature used to control the public server endpoint returned to clients during Well-known discovery.
# You should only use this if you want mobile apps to access the immich API over a custom URL. Do not include trailing slash.
# NOTE: At this time, the web app will not be affected by this setting and will continue to use the relative path: /api
# Examples: http://localhost:3001, http://immich-api.example.com, etc
####################################################################################

#IMMICH_API_URL_EXTERNAL=http://localhost:3001
```

### Reproduction steps

Use the Immich app on a Samsung Galaxy S22 Ultra (Android).
Go to an album or timeline containing older iPhone 13 Pro Max videos (uploaded before December 2024).
Attempt to open/play one of these videos.

    Observed behavior: The app either crashes immediately or the video displays with an incorrect aspect ratio.

Repeat on an iPhone 13 Pro Max.

    Observed behavior: The video may show an incorrect aspect ratio, but does not crash.

### Relevant log output

```shell
No errors on server side
```

### Additional information

![Image](https://github.com/user-attachments/assets/f35df3a5-e3c8-46a9-87b6-8fd77bb79b73)

**Comment by bo0tzz** [comment]
> It appears the fix included in PR https://github.com/immich-app/immich/pull/12104 doesn’t apply retroactively to older uploads.

It certainly would. Can you give more detail? Does this happen on all videos, are these videos remote only or stored on the device, do they work in a web browser, have you changed any of the transcoding settings?

**Comment by mosalski** [comment]
Yes, this is affecting all videos uploaded before the fix. Specifically:

-   Samsung Galaxy S22 Ultra (Android): The older videos are remote, and they exhibit both an incorrect aspect ratio and sometimes app crashes when opened.
-   iPhone 13 Pro Max (iOS): The same older iPhone videos (both local and remote) only show incorrect aspect ratio—no crashes on iOS.
-   Web Browser: All these older videos work fine in the browser without aspect ratio issues or crashes.
-   Transcoding Settings: Everything is currently at the default settings.

![Image](https://github.com/user-attachments/assets/63a4a833-6994-45a3-8f5f-d054e1cad738)

**Comment by mosalski** [comment]
Additional Note

Around last fall, this issue did not occur. Videos recorded on an iPhone displayed correctly on a Samsung device at that time. Unfortunately, I can’t pinpoint the exact date or build when the bug first appeared, but it definitely wasn’t present back then.

**Comment by mertalev** [comment]
Have you tried signing out and signing back in?

**Comment by mosalski** [comment]
Yes, I tried signing out and back in, but it did not resolve the issue.

**Comment by Flatcore-code** [comment]
Hello,
I have the same Problem on a Google Pixel 8 Pro.
When I try to watch the videos I made last year with a Xiaomi Note 10 Pro, it distorts (see screenshot).
The videos are not local to the Google Pixel.
When I download the video it works as desired.

When I call up the video on the Google Pixel via the web browser (Chrome), it also works as desired.

I have already tested various transcoding settings but without success.

![Image](https://github.com/user-attachments/assets/9266cc7f-834a-45fb-a3d3-ab89c200b706)

**Comment by Flatcore-code** [comment]
Ok, I have found a solution.
Actually, I just ran “EXTRACT METADATA” - "All" under Jobs and the correct resolution was set.
I was sure I had already tried that but I was probably mistaken.

![Image](https://github.com/user-attachments/assets/ff28e042-7542-4621-b38c-fea8f84e997c)

**Comment by mosalski** [comment]
I tried the solution mentioned by @Flatcore-code: running "EXTRACT METADATA" - "All" under Jobs.

After doing this:

-     On iPhone 13 Pro Max, everything now works correctly, and videos play as expected.
-     On Android (Samsung Galaxy S22 Ultra), the app no longer crashes when opening older iPhone-recorded videos. However, instead of playing, the video gets stuck on an infinite loading bar and never starts.

**Comment by mosalski** [comment]
@bo0tzz Is there any update on this? May be an investigation needs to be planned?

**Comment by SynthwaveFox** [comment]
I can also confirm, except for me its EVERY video in my library, regardless of source. I have videos from phones, web, screen recordings, everywhere, and not a single one displays correctly. Some are in a square ratio, 4:3, stretched or squished. Playing the same videos in a web browser version of my immich instance works just fine.

**Comment by kevinkdev** [comment]
Any info on this? I am also experiencing the same issue on a Google pixel 7 pro. Run extract metadata for all, running latest server docker image with the tag main. Also did log out and log back in, but the issue is still there, the aspect ratio of videos done by others is wrong. My videos done with pixel 7 pro, are displaying just fine, even without being locally saved.

**Comment by Blendi** [comment]
+1

**Comment by serialx** [comment]
I had this exact problem, deleted everything and reinstalled. Reuploaded and it was fixed. (Kinda, there are some issues with large video file. See PR #24094  )

My observation is similar to #23890 . When I lower the concurrency on the thumbnail and metadata generation jobs, more videos get correct metadata.

**Comment by pfr-dev** [comment]
This happens for me on all videos searched through filters (file type, people etc) regardless of when they were recorded or uploaded.

**Comment by LeLunZ** [comment]
@bo0tzz @mosalski  Just want to chime in here. 

I came here from #23928 but I am not sure if it’s the same. 
Here in the issue description @mosalski talks about a fix not applying retroactively. 
But I haven’t even had Immich installed for this long, and I still have the issue. 

Additionally for me the videos work as they should in the normal timeline, it’s just that the aspect ratio **always** crops in the search tab. 
(I tested this with a video that’s only on the Immich instance and not on my phone) and that’s regardless of which phone took the photo, when it was taken or other stuff. 

So I am not sure if it’s a metadata issue, as it works in the timeline…

**Comment by mat-sienczyk** [comment]
I have the same issue on Android app - videos in search are distorted, they are originals tho, so no transcoded (I have option to only transcode videos in unsupported codec). Does not matter if they are from phone or camera. I run the "EXTRACT METADATA", does not helped.

**Comment by joonon** [comment]
The OS that Immich Server is running on
Ubuntu 22.04.5 LTS

Version of Immich Server
v2.3.1

Version of Immich Mobile App
v2.3.1

Platform with the issue

Server

Web

Mobile
✅ iOS 26.1

I've run the metadata extract on the server and logged out and back in on the mobile client and the issue persists. It only occurs when looking at videos via any kind of a search but it happens to ALL of them at that point, it doesn't matter the age. If I use the "people" library to filter a person and look at a video via that method, the aspect ratio is correct but if I go into search and filter by that same user, the aspect ratio of all videos will be incorrect. I can't tell you exactly when this problem started but it's been at least a month or so for me.

**Comment by pfr-dev** [comment]
Appears to be fixed for me in the latest build 2.4.0 on Android 16

**Comment by oloev** [comment]
2.4.0 doesn't fix for me, aspect ratio still wrong when searching with filters

**Comment by LeLunZ** [comment]
@oloev did you update the app too, because I think this was a bug in the app code?

**Comment by oloev** [comment]
> [@oloev](https://github.com/oloev) did you update the app too, because I think this was a bug in the app code?

There was no update available yet when I wrote the post, now app is updated and I can confirm the issue doesn't occur. Thanks!

**Comment by mat-sienczyk** [comment]
Unfortunately, for me it still occurs - I have android and videos from search are distorted. 

Latest version both server and app (2.4.1).

<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/091c1039-298f-41a0-9462-9120e73ed997" />
