### ISSUE TITLE
Search using /api/search/metadata endpoint does not return stacked which an asset is part of

### ISSUE THREAD

**Issue by dwlfrth** [immich-app/immich#16180]
### The bug

Searching using /api/search/metadata endpoint along with the "withStacked" option to true does not behave accordingly. I have two assets that are stacked together and both belong to the same tag. I am using the endpoint to search for the tagID.
Result is both assets but no mention of stack anywhere.

### The OS that Immich Server is running on

Docker

### Version of Immich Server

v1.126.1

### Version of Immich Mobile App

n/a

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
pristine
```

### Your .env content

```Shell
pristine
```

### Reproduction steps

1. Add a tag to two assets
2. Stack them together
3. Search using the /api/search/metadata endpoint with query for tagIds and "withStacked" set to true
...

### Relevant log output

```shell

```

**Comment by dwlfrth** [comment]
Is there any way to know whether or not this is on a roadmap ?
It looks like a bug to me since the query parameter exists but nothing is being returned :(

**Comment by mattdavis90** [comment]
From what I can tell it got removed from [this function](https://github.com/immich-app/immich/blob/bb72d723e25fcf886ab7556d4a9d4b57fbfe36e6/server/src/utils/database.ts#L304) at some point.

I own the [immich-stacker](https://github.com/mattdavis90/immich-stacker) repo and had noticed that in the last few releases (since maybe 1.135.0) that the code has been trying to re-stack every image in my library because the server doesn't appear to care about this parameter.

I think it got lost in the move to Kysely https://github.com/immich-app/immich/commit/2e12c46980b45072beb0f4ba125f821053b13851#diff-86ab2a4a498d384c7d5d3b7ee8faea7907117a6655c1a6eda94ca84f481dc361R268-R271

**Comment by meesfrensel** [comment]
Fixed in #26607

**Comment by 190n** [comment]
#26607 made it so that setting `withStacked: false` will exclude assets that are part of a stack, but I think this issue was asking for `withStacked: true` to include the `stack` property on assets in the search response, which still doesn't happen on 3.2.2. Should I open another issue or will someone reopen this?
