### ISSUE TITLE
Storage template migration doesn't move Live Photo videos (mov files)

### ISSUE THREAD

**Issue by guido1981** [immich-app/immich#17668]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Storage template migration doesn't move Live Photo videos (mov files) to the album folder, but leaves them in Other

### The OS that Immich Server is running on

Synology DSM 7.2

### Version of Immich Server

1.131.3

### Version of Immich Mobile App

1.131.3 build.201

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
.
```

### Your .env content

```Shell
.
```

### Reproduction steps

I have tried everything. Uploading new live photo with web ui, or with the IOS app
Or  moving existing live photos with the task Storage template migration. 

![Image](https://github.com/user-attachments/assets/d15cd602-db1d-46c9-b461-1774e7fe8055)

The mov files remain in the Other folder while the jpgs/heic files are moved to an album folder.

![Image](https://github.com/user-attachments/assets/e7053239-44b0-425a-ba4c-4bfe63514481)

![Image](https://github.com/user-attachments/assets/6501688d-95a8-432e-bb36-629ab633fe42)

### Relevant log output

```shell

```

**Comment by zackpollard** [comment]
This is fixed in main and will be included in the next release.

**Comment by guido1981** [comment]
Which release will it be fixed in?

**Comment by killayaw** [comment]
This is still broke as of v1.135.3. I don't see in any release notes where this was resolved. Please reopen this issue.

**Comment by danieldietzler** [comment]
This has not been fixed. We only add the image-asset to the album and as such the storage template won't move the .mov file to the same folder if the template uses an album

**Comment by killayaw** [comment]
Just noticed that this seems to work properly for images with the .jpg extension. The associated .mov files are correctly moved into the album folder with the image as per the storage template. However, this does not work correctly for images with the .heic extension. The associated .mov files are not correctly moved to the album folder.

**Comment by HolyMacarony** [comment]
> Just noticed that this seems to work properly for images with the .jpg extension. The associated .mov files are correctly moved into the album folder with the image as per the storage template. However, this does not work correctly for images with the .heic extension. The associated .mov files are not correctly moved to the album folder.

exactly. The problem still persists for heic live photos.

**Comment by TheEnigmist** [comment]
I was about to open this issue for .HEIC file and come here, so the issue still persist as v1.137.3

**Comment by hoplie88** [comment]
I just checked, the issue still persists as v1.138.0.

**Comment by danieldietzler** [comment]
Y'all don't need to post updates after every release now :D We're aware that this is still an issue, otherwise it would be closed

**Comment by romancin** [comment]
I have just started using Immich, and I still see this problem exists. As I need to start importing all my photos, I need to ensure this question before doing it: When this problem is fixed, will all the .mov files migrated to the album folder automatically and the “month” directories will be deleted? Or do I need to trigger any kind of migration manually?

Thank you in advance!

**Comment by danieldietzler** [comment]
Given we don't have a fix for it yet it's hard to tell, but I'd expect you'll need to re-run the template migration job.

**Comment by romancin** [comment]
> Given we don't have a fix for it yet it's hard to tell, but I'd expect you'll need to re-run the template migration job.

Thank you for the response. Knowing it can be fixed, I will start the migration then :)

**Comment by killayaw** [comment]
Any update on this?

**Comment by danieldietzler** [comment]
@killayaw https://justinmayer.com/posts/any-updates

**Comment by NikhilAlapati** [comment]
Created a PR to address this issue https://github.com/immich-app/immich/pull/24688

**Comment by vakarian92** [comment]
Hello, I am still affected by this bug in the latest version v2.5.6, should I create a new issue?

**Comment by danieldietzler** [comment]
@vakarian92 no, we're already aware. #25329 will fix it
