### ISSUE TITLE
Items moved to Locked Folder on web view aren't visible through ios mobile app

### ISSUE THREAD

**Issue by jahopki** [immich-app/immich#18484]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Images moved to Locked Folder via Chrome browser are not visible in Locked Folder of the ios (iphone 13Pro) app.

### The OS that Immich Server is running on

Ubuntu 24.04.2

### Version of Immich Server

v1.133.0

### Version of Immich Mobile App

1.133.0 build.206

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
#    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    image: docker.io/valkey/valkey:8-bookworm@sha256:42cba146593a5ea9a622002c1b7cba5da7be248650cbb64ecb9c6c33d29794b1
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      DB_STORAGE_TYPE: 'SSD'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/ssd/photos
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=America/Chicago

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=immichPostgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

After updating to 1.133.0, I was excited to make use of the Locked Folders feature. I updated my Immich instance and my app on iOS. Then using Chrome, I moved a handful of pictures to the Locked Folder (after setting a PIN). I then opened the app on my iPhone 13 Pro, navigated to Libraries -> Locked Folders, and was disappointed that nothing was present.

### Relevant log output

```shell

```

**Comment by jahopki** [comment]
as further detail, when I use the mobile app to scroll to the date of the images that were moved to the locked folder, I see blurred thumbnails with an exclamation point in a circle in place of each image that was moved.

**Comment by alextran1502** [comment]
Did you open the app while the move was happening? pull down to refresh from the home page should fix it

**Comment by jahopki** [comment]
The app was closed on my phone while I was selecting and moving photos to the locked folder through a Chrome browser on a laptop. I've tried pulling down from the Locked Folder view in the app (nothing happens). I've also gone to the Photos view (which I assume is the "Home" page), pulled down, navigated back to Library -> Locked Folder, and still don't see the images I moved to the Locked Folder. I just see a message that reads "Photos and videos in Locked Folder are hidden and won't show up as you browser [sic] your library."

**Comment by jahopki** [comment]
FWIW: I've restarted both my Immich server instance and the app on my phone. The results remain the same: images moved to the Locked Folder are visible in the Chrome browser on a laptop, the Locked Folder in the app on my iPhone is empty, and thethumbnails in the Photos section of the iPhone app are blurred.

**Comment by jahopki** [comment]
more detail: when I use Chrome on my iphone instead of the Immich app and navigate to the Locked Folder option, the images are visible as expected. I also just realized that the images I put into the Locked Folder are all gifs. With that in mind, I tried moving a regular JPG to the Locked Folder; the behavior is the same. I see the image in the Locked Folder through a Chrome browser but do not see it through the ios app.

**Comment by alextran1502** [comment]
@jahopki Can you try log out and log back in? The migration might not run correctly

**Comment by jahopki** [comment]
@alextran1502 That fixed it. I logged out of the Immich app on my iphone. Logged back in and navigated to the Locked Folder option under Library. I entered my PIN when prompted and now I see the images. Also, the previously blurred thumbnails in the photo timeline are no longer present.

**Comment by alextran1502** [comment]
should be good now with logout and log back in
