### ISSUE TITLE
[beta] Android: remote deletions are reuploaded after having cleared trash

### ISSUE THREAD

**Issue by kapuett** [immich-app/immich#20978]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

On v1.138.0 with "sync remote deletions" enabled in beta timeline, assets are reuploaded to the server after having cleared the trash.

### The OS that Immich Server is running on

Debian GNU/Linux 12 (bookworm)

### Version of Immich Server

v1.138.0

### Version of Immich Mobile App

v1.138.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich:
    container_name: immich
    image: ghcr.io/immich-app/immich-server:v1.138.0
    volumes:
      - /mnt/container_workload/immich/lib:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DB_PASSWORD_FILE=/run/secrets/db_password
      - DB_USERNAME=postgres
      - DB_DATABASE_NAME=immich
    devices:
      - /dev/dri:/dev/dri
    depends_on:
      - redis
      - database
    restart: unless-stopped
    secrets:
      - db_password
    networks:
      - immich
      - proxy
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:v1.138.0
    volumes:
      - model-cache:/cache
    restart: unless-stopped
    networks:
      - immich
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:42cba146593a5ea9a622002c1b7cba5da7be248650cbb64ecb9c6c33d29794b1
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped
    networks:
      - immich

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - /mnt/container_workload/immich/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - immich
    secrets:
      - db_password
    labels:
      wud.watch: false

secrets:
  db_password:
    file: /mnt/container_workload/immich/postgres.txt

networks:
  immich:
  proxy:
    external: true
volumes:
  model-cache:
```

### Your .env content

```Shell
Included in secrets/env vars of compose
```

### Reproduction steps

1. Take picture on mobile and wait for it to be synched
2. Delete that picture on immich web and wait for it to disappear from mobile
3. Clear trash
4. Restart android app and wait for picture to reappear on mobile and server

### Relevant log output

```shell

```

### Additional information

I have "Reset SQLite Database" on mobile, logged out and re-setup sync again with the same results.

**Comment by MichScha** [comment]
Just wanted to open an issue - same behavior for me with same setup.

**Comment by kapuett** [comment]
Removed [beta] from title as still exists with `1.42.0`

**Comment by XobSod** [comment]
Can confirm for `1.143.1`

**Comment by ObsidianMaximus** [comment]
Issue still exists in v2.0.0 - Stable Release

**Comment by alextran1502** [comment]
There are WIP to port the feature over to the new timeline

**Comment by ronzino83** [comment]
Two ways sync seems to does not work anymore in beta timeline.
Two way sync = if an asset is removed from smarpthone gallery app it will be deleted on immich server (web and app) AND if an asset is removed from immich server (using the app or the web) it will be deleted on smartphone as well.

Please add back this feature

**Comment by ncsufan8628** [comment]
also having this issue and remote deletions not syncing on v2 and Android

**Comment by effsee00** [comment]
Commenting to note issue is still present and to add additional **FINE** level app logging if helpful.

Android App Version: 2.1.0 build.3022
Server: v2.1.0
App setting: Sync remote deletions [EXPERIMENTAL] =TRUE

[Immich_log_2025-10-25T11_28_34.688565.log](https://github.com/user-attachments/files/23141424/Immich_log_2025-10-25T11_28_34.688565.log)

**Comment by ronzino83** [comment]
I wonder why this deletion problem is not the top priority of developers and not in the to do list as well. I stopped using my server waiting for a fix due to this.

**Comment by rokfor2000** [comment]
So did I. 

Really annoying, especially if you use Immich on more than 1 device. I need to remember on which device the photo was taken to be able to permanently delete it...

**Comment by schildbach** [comment]
Is this really limited to remote deletion? What does "remote" actually mean in this context, the web app is also remote.

I came to this report because if I delete an image via the webapp, then clear trash, the image gets reuploaded by the Android app automatically. So effectively I can't delete photos any more.

**Comment by effsee00** [comment]
> I wonder why this deletion problem is not the top priority of developers and not in the to do list as well. I stopped using my server waiting for a fix due to this.

Whilst not an ideal solution, as a workaround I've set my Trash auto-deletion to be 9999 days.  This way I don't get 'deleted' images reappearing into my feed.  I'm not pressed for storage space, so my deletions have 27 years to sit in the trash until this is resolved.

**Comment by ronzino83** [comment]
Problem is not limited to pictures that reappear. It is also impossible to keep in sync pictures on smartphone and server as where ever you remove them, they are not removed on the other side.

**Comment by kapuett** [comment]
> It is also impossible to keep in sync pictures on smartphone and server as where ever you remove them, they are not removed on the other side.

This works for me. Deleting only isn't synched from the server -> client. If I remove the assets from the device where they were created, they are deleted from both, server and client.

**Comment by effsee00** [comment]
You're right they are not deleted from either device.  So far I see the scenario as: 

- Immich backs up image from Android device to server OK. 
a) 'Trash' the image from Immich mobile app or web UI - changes synced between Immich views and it is no longer shown in the feed. However the original image is still present at the original location in device filesystem and visable by other image apps. 
b) 'Delete' the image from Immich trash, and the deletion is not replicated outside of Immich to the device filesystem.  The original image is re-synced into Immich. 
c) Using a 3rd party application to delete an image from the Android device will successfully delete the original image, and Immich's backup of this image is _not_ affected - illustrated with the image still shown in the mobile app, but with only a 'cloud without tick' icon overlay. 

It does seem strange this bug is prioritised as "Low" given that this does severely affect the ability to organise images locally.

**Comment by kapuett** [comment]
> You're right they are not deleted from either device. 

That's not the case for this issue. Please open a separate one if it is for you.

> It does seem strange this bug is prioritised as "Low" given that this does severely affect the ability to organise images locally.

Even in the title of the option it says "EXPERIMENTALLY", so it makes sense this is not a prio issue.

**Comment by ronzino83** [comment]
> That's not the case for this issue. Please open a separate one if it is for you.

I did it was closed as duplicate of this. So here we are

> Even in the title of the option it says "EXPERIMENTALLY", so it makes sense this is not a prio issue.

I know.... But le me ask.... How a problem that breaks the user experience (you cannot delede assets) can be low priority ? Lower then developing image editor ? I wonder how you can delete wrongly edited images then 🤣

**Comment by XobSod** [comment]
There is even a feature that allows you to remove duplicated photos (similar photos, taken within short period of time), but what sense does it make to use it, if the photos get reuploaded after you delete them ;)

**Comment by effsee00** [comment]
>> You're right they are not deleted from either device.

> That's not the case for this issue. Please open a separate one if it is for you.

Your reproduction step #4 seems to suggest this is exactly the same issue.  To be clear in my statement - the images are not being removed from the local device filesystem, which results in the image being re-uploaded when you clear the trash.  

Despite it being an experimental feature, it doesn't stop it being important functionality.  Regression of experimental features could still be considered important to many.  It's reassuring that @alextran1502 has noted there _is_ work in progress to fix it.

**Comment by ncsufan8628** [comment]
has anyone tried to revert to an older version where the delete functionality actually works?  

really sucks and makes immich unusable to not be able to remove trash assets or use my PC to clean up unwanted assets and have them removed from the phone itself

**Comment by ronzino83** [comment]
> has anyone tried to revert to an older version where the delete functionality actually works?
> 
 The risk to mess the db is big doing this. And old immich versions where delete used to work have the auto sync function that does not as well as problems to keep track of already uploaded assets.

**Comment by ncsufan8628** [comment]
So I have a workaround - turns out its not the immich server that has the issue, its the android app.  Downgrading my android app to v1.135 has solved my issue with remote deletions not syncing between devices.

**Comment by rokfor2000** [comment]
> So I have a workaround - turns out its not the immich server that has the issue, its the android app. Downgrading my android app to v1.135 has solved my issue with remote deletions not syncing between devices.

Really hopeful! Will give it a go tomorrow.

**Comment by ncsufan8628** [comment]
good luck! hope it helps.  There may be a more recent version that works too - I just remember the feature working when I first migrated to immich at the start of the summer so picked that one when the latest couple releases prior to v2 didnt work.

**Comment by ObsidianMaximus** [comment]
If I can recall correctly, it was the android app that was broken since the new UI came.

Before this UI, the old one had no issues, but we had an option in the app to enable the new interface (which was in beta back then) and that had same issues with remote deletions. 

So yeah, reverting to any version with the old UI should fix it.

**Comment by rokfor2000** [comment]
I have switched to the old timeline in the new app hoping it'd fix it, but unfortunately it didn't I thought this is what you referred talking about a new UI, but it seems there must have been some previous UI change as well?

**Comment by schildbach** [comment]
This bug is still present in Immich Server 2.2.0.

**Comment by rokfor2000** [comment]
There's always a silver lining 2.2.0 has [Web] UI improvement for the review duplicates screen. Which is important because we gonna have to delete the same duplicates over and over 😂

Anyway I was testing trying to decide if I should switch to Immich and apart from this (rather annoying) bug, I really like it. I'm going to make a leap of faith ... hopefully will be resolved soon.

**Comment by Nevaehni** [comment]
Issue still exists with v2.2.3

**Comment by smrky1** [comment]
I believe the issue is now fixed starting from 2.3.0. Tested with 2.3.1 today and when I delete an asset through web app and then clear the Trash, it is removed* on my Android phone as well and will not get re-uploaded.

*it is actually not removed from the device, but the filename is prepended with ".trashed-". I believe this is the desired behaviour (as it is the same as how Google Photos trash works). Although I did not figure out when / how are the .trashed- files eventually deleted from the device file system.

**Comment by HaDeSMonsta** [comment]
At least on my Samsung it is actually moved to the internal trash and marked for deletion in 30 days, so this is probably how your phone handles trashed files (?) 
> *it is actually not removed from the device, but the filename is prepended with ".trashed-". I believe this is the desired behaviour (as it is the same as how Google Photos trash works). Although I did not figure out when / how are the .trashed- files eventually deleted from the device file system.

**Comment by smrky1** [comment]
Seems the ".trashed-" files are automatically deleted by either Google Photos / Google Files app or by Anroid OS itself (after 30 days).

After emptying the Trash in Immich, I can still see the assets show up in Google Photos / Google Files Trash (those are the ".trashed-" file in my file system).

When I empty the Trash in either of the Google Apps, they are gone for good (happens automatically after 30 days as it says in those apps). I cannot quickly verify if they get removed even if you do not have either of the Google apps installed (maybe Android OS clear them automatically).

Anyways I can revert my 9999 days period for emptying Immich Trash back to default 30 as the issue is finally fixed :-) Thanks!

**Comment by kapuett** [comment]
Can confirm this as fixed with v2.3, closing the issue.

**Comment by dpad** [comment]
I'm sorry to comment on this supposedly closed ticket, but it still seems to not be working correctly for me.
I've updated to Server v2.3.1 and App v2.3.0.build.3027.

Behaviour I'm still seeing:

1. I took some photos on my phone.
2. The photos get uploaded to the Immich server (cloud icon with a tick).
3. I delete them from the web UI directly (not from the app).
4. I got to "Trash" on the web UI and delete them permanently.
5. On the app, the photos now show up as not uploaded (cloud with a cross).
6. The app again uploads them to the server (cloud with tick).

I can repeat this any number of times and the photos never delete, they keep re-uploading.

Is there some new setting I'm missing? Do I need to clear some kind of cache?

**Comment by effsee00** [comment]
> I'm sorry to comment on this supposedly closed ticket, but it still seems to not be working correctly for me. I've updated to Server v2.3.1 and App v2.3.0.build.3027.
> 
> Behaviour I'm still seeing:
> 
> 1. I took some photos on my phone.
> 2. The photos get uploaded to the Immich server (cloud icon with a tick).
> 3. I delete them from the web UI directly (not from the app).
> 4. I got to "Trash" on the web UI and delete them permanently.
> 5. On the app, the photos now show up as not uploaded (cloud with a cross).
> 6. The app again uploads them to the server (cloud with tick).
> 
> I can repeat this any number of times and the photos never delete, they keep re-uploading.
> 
> Is there some new setting I'm missing? Do I need to clear some kind of cache?

I can reproduce what you're doing, and assume you're not allowing the changes to sync to the phone. 

Updated steps:
3. I delete them from the web UI directly (not from the app).
3b. Open immich app allow changes to sync.
3c. Observe images get removed from Immich view, and phone native image app
4. I got to "Trash" on the web UI and delete them permanently.
4b. Open immich app allow changes to sync.
5. photos still deleted.

It seems the process flow for deletions, the mobile app needs to be aware of the image going into Trash.  In a normal flow the images would likely sit in trash for x number of days (before being deleted automatically) and this sync would happen normally.  

I imagine that the scenario you're testing this with (send to trash, and delete from trash within a few minutes) is an edge case that the flow isn't engineered for.

**Comment by schildbach** [comment]
> I imagine that the scenario you're testing this with (send to trash, and delete from trash within a few minutes) is an edge case that the flow isn't engineered for.

That would be unfortunate. I think emptying the trash just after trashing a photo is a very common usecase. Maybe you don't do it for every trashed photo, but every now and then there is a photo you really want to make sure it's gone.

**Comment by effsee00** [comment]
> > I imagine that the scenario you're testing this with (send to trash, and delete from trash within a few minutes) is an edge case that the flow isn't engineered for.
> 
> That would be unfortunate. I think emptying the trash just after trashing a photo is a very common usecase. Maybe you don't do it for every trashed photo, but every now and then there is a photo you really want to make sure it's gone.

Agreed - it's a poor user experience in that case, so possibly still a bug.  Would be good to get clarification of expected behaviour from the devs.  

@alextran1502

**Comment by kapuett** [comment]
Cannot reproduce what is described here. Images are not uploaded again like in the original issue description. I can clear trash immediately after the image vanished from Android App and it is not uploaded again. @dpad just to be sure: you do have the remote sync feature activated in the app, right? Did you log out from the app and tried again?

**Comment by dpad** [comment]
@kapuett Thanks for checking! Sync remote is enabled (as far as I understand it) --> the "Sync Status" screen shows a tick next to the Sync Remote job. I did not log out from the app, so I'll try that now and report back...

(Below is after having logged out and back in to the app.)

First I tried deleting on web UI then immediately clearing trash: Immediately reuploaded.

Next I tried deleting on web UI, then waiting for the app to sync (deleted image disappeared from app), then cleared trash on web UI. This time the image seems to stay deleted. So I think @effsee00 is possibly right.

**Comment by smrky1** [comment]
> First I tried deleting on web UI then immediately clearing trash: Immediately reuploaded.

This is the issue. You are not allowing the Android app to synchronize and to find out that you 1) trashed the image in the web app 2) emptied trash in the web app. Seems the Android app evaluates it as a completely new image and reuploads. I can reproduce it now...

In other words it only becomes a problem if you empty the trash in the web app before allowing the mobile app to synchronize.

**Comment by schildbach** [comment]
This issue is back. Suddenly photos that I deleted over months re-appeared in the web interface. They are not visible in the app however, so the two are not in sync any more. I'm on the most recent versions of both server and app. Can someone reopen?

**Comment by kapuett** [comment]
@schildbach do you have steps to reproduce? I can't reproduce the initial issue I reported here. What I tried just now to verify:

1. Take pictures on phone
2. Wait until synched to server
3. Delete from server via GUI in browser
4. Wait until deletions synched to mobile
5. Delete from trash in server via GUI in browser
6. Pictures stay deleted from mobile and are not reuploaded. Also gone from trash in mobile app.

If you still face issues, it's probably best to open a new issue.

**Comment by schildbach** [comment]
1. I had the web site open and noticed that a couple of new photos haven't yet been synched from the Android app.
2. So I opened the Android app to sync. I've done this many times since this issue was closed and it worked as expected.
3. This time, it synched not only new photos but somehow undeleted tons of photos I have already deleted during the past weeks.
4. I'm now working on deleting all the already deleted photos again. 

Note this matches the description of this issue quite closely, doesn't it? I assume it's not fully fixed yet.

**Comment by schildbach** [comment]
This issue is not fixed on Immich version 2.6.0.

**Comment by schildbach** [comment]
It's really easy to reproduce: delete one or more images from web (the images disappear from mobile as well), empty trash, restart the app. The images re-appear in the app and have the "cloud backup missing" icon. Cloud sync kicks in and re-uploads the images, making them appear on the web as well.

How can I permanently delete images in Immich?

**Comment by kapuett** [comment]
I cannot reproduce. Your provided steps work as designed for me: assets moved to system trash on Android and are not reuploaded. 
You sure you have the flag "Sync remote deletions [EXPERIMENTAL]" set in the Android app?

**Comment by schildbach** [comment]
> You sure you have the flag "Sync remote deletions [EXPERIMENTAL]" set in the Android app?

Yes, it's enabled.

**Comment by smrky1** [comment]
> It's really easy to reproduce: delete one or more images from web (the images disappear from mobile as well), empty trash,

I can reproduce, but it is important to note that the full steps to reproduce are: take picture with phone, let Immich synch / upload, close mobile app, delete image from web, empty trash in web app (do not let the mobile app synch), open mobile app: the image will be marked as new, not yet uploaded and will upload with the next synch.

And this "workflow" has already been discussed in this ticket: https://github.com/immich-app/immich/issues/20978#issuecomment-3566440478 (read the following comments). It is not ideal, but it is a different issue than what had originally been reported under this Bug report. I recommend filing a new Bug report / Feature request.

**Comment by welcometopwn** [comment]
Same issue for me on Android. Deleted around 400 pictures on the web, emptied trash and when i opened the app on my phone they all reappeared. Sync remote deletion "Experimental" is enabled.

**Comment by ronzino83** [comment]
Is not clear why this bug is still open for everybody but not for the developers. One year has passed, un useful features added, but a major bug was never taken into account

**Comment by alextran1502** [comment]
Hello, revisiting this topic after a ping. 

This is currently working as expected. If you are trashing the asset, then immediately clear the trash before opening the mobile app with the _experimental_ sync deletion enabled, by clearing the trash, there is no record left in the database, so the sync deletion doesn't actually see anything to sync-delete. 

Understanding this is a limitation, regardless, there are some WIP that are trying to address this scenario; however, they are lower in the priority of the team at the moment.

**Comment by ronzino83** [comment]
Thanks for answering. Waiting for this for months.

Let me says.... Priorities should be driven also by user experiences and feedbacks quantity. Several topics that reports this as a problem with a lot of replies that remarks this, should suggest that it is not just a single user need, but something that should be revised.

Data consistency should  always come first then everything in every software. A deleted asset that actually is not or that respwans I am not that sure that can be considered low priority for 1 year. 

Having a time counter that impose you to rush to delete an asset from a device before synchronization, apart that is not an elegant solution as look like as a quick workaround, but it is also hard to explain to "Not so digital addicted"  users. 

In any case thanks for your work and support. Hope dev team change it's mind and give to this isusse a top priority after so much time.

**Comment by alextran1502** [comment]
> Let me says.... Priorities should be driven also by user experiences and feedbacks quantity. Several topics that reports this as a problem with a lot of replies that remarks this, should suggest that it is not just a single user need, but something that should be revised.

If you read through the various discussion topics in the project, you can see a dozen other topics that are asking for the same priority for implementation or fixing. The specific feature has lower priority because 

1. There is a workaround by trashing the assets, then opening the mobile app to sync deletion before clearing the trash
2. The nature of the "Experimental" tag on a feature.

Regardless, we are aware of the issue and will work on a fix as capacity allowed

**Comment by ronzino83** [comment]
> > 
> 1. There is a workaround by trashing the assets, then opening the mobile app to sync deletion before clearing the trash

This workaround just work for reappering assets. Does not solve the problem of assets that are deleted from phone and not from server. When I take pictures most of the time a don't have time to revise them before an immich sync. The immich purpose is to backup assets so it should run everyday automatically in background. 
I would like to avoid to sync pictures I need just for a second or for some days (pictures for work puporse) and I would like not to mix them on backups with family pictures. 

That second workaround is harder to apply then the one for the other problem. 

In any case thanks I will wait for a fix but just because better alternatives then immich doen to exist at the moment.
