### ISSUE TITLE
Phone locks up when opening an image in the Android app

### ISSUE THREAD

**Issue by UnknownError235** [immich-app/immich#21159]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

When I click on a photo in the immich app, I see a low resolution version. Then my phone freezes and becomes unresponsive. Sometimes my phone even reboots. The images are 64 mega pixels so maybe a performance issue.

### The OS that Immich Server is running on

Arch

### Version of Immich Server

v1.139.2

### Version of Immich Mobile App

v1.138.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Device make and model

Samsung A71 Android 13

### Your docker-compose.yml content

```YAML
#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cuda # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:facc1d2c3462975c34e10fccb167bfa92b0e0dbd992fc282c29a61c3243afb11
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:32324a2f41df5de9efe1af166b7008c3f55646f8d0e00d9550c16c9822366b4a
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    shm_size: 128mb
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The location where your database files are stored. Network shares are not supported for the database
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Open the app
2. click on a synced image that is 64MP
3. my phone now freezes after a few seconds
...

### Relevant log output

```shell
PlatformDispatcher - Catch all

Bad state: Stream has been disposed.
An ImageStream is considered disposed once at least one listener has been added and subsequently all listeners have been removed and no handles are outstanding from the keepAlive method.
To resolve this error, maintain at least one listener on the stream, or create an ImageStreamCompleterHandle from the keepAlive method, or create a new stream for the image.

#0      ImageStreamCompleter._checkDisposed (package:flutter/src/painting/image_stream.dart:698)
#1      ImageStreamCompleter.setImage (package:flutter/src/painting/image_stream.dart:732)
#2      OneFramePlaceholderImageStreamCompleter._onImage (package:immich_mobile/presentation/widgets/images/one_frame_multi_image_stream_completer.dart:39)
#3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1778)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:381)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:312)
#6      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:798)
#7      _StreamController._add (dart:async/stream_controller.dart:663)
#8      _StreamController.add (dart:async/stream_controller.dart:618)
#9      _AsyncStarStreamController.add (dart:async-patch/async_patch.dart:81)
#10     _StreamIterator.current (dart:async/stream_impl.dart)
#11     LocalFullImageProvider._codec (package:immich_mobile/presentation/widgets/images/local_image_provider.dart:139)
<asynchronous suspension>
#12     OneFramePlaceholderImageStreamCompleter._onImage (package:immich_mobile/presentation/widgets/images/one_frame_multi_image_stream_completer.dart:38)
<asynchronous suspension>
```

**Comment by alextran1502** [comment]
cc @mertalev 

Hello, can you help me confirm if this is reproducible all the time?

**Comment by UnknownError235** [comment]
yes this happens every time when I try to open an image in the app.

**Comment by N8-Yue** [comment]
The only issue that I have are extremely low resolution thumbnails which weren't existing like that before but my app does not crash at all

**Comment by UnknownError235** [comment]
Okay small update:
1. This also happens if the server is offline.
2. After I close immich I usually get a system UI is not responding but I just got a `Proces system` not responding error.

**Comment by UnknownError235** [comment]
Also it's not that my app crashes but that my phone stops responding.

**Comment by mertalev** [comment]
The issue should not be that you have 64MP images - your phone has enough RAM for 64MP to not be an issue, and the app wouldn't load them at that resolution anyway. The error message shows a clear bug that should be fixed, but there isn't a good reason for that to cause an OS-level crash. I suppose it's a driver bug or something.

**Comment by UnknownError235** [comment]
I used `adb shell top` to see what the bottleneck on my phone is, and it looks like cpu usage goes up to 100%. If I need to try anything else with adb to debug this, just let me know :)

<img width="798" height="138" alt="Image" src="https://github.com/user-attachments/assets/a2d827ed-d10a-4184-9896-379338945a0c" />

**Comment by mertalev** [comment]
That's 100% of a single core, not overall CPU usage, right? That seems normal. Although 2.2GB is on the high side.

Can you try taking a lower res image, making sure it's the first thing in the timeline, and opening it? If it works, then swipe to the right 64MP image. If that works, then slowly continue swiping and gradually increase the speed.

**Comment by mertalev** [comment]
Also, which version of the A71 do you have? There is the 4G, 5G and 5G UW that have different specs.

**Comment by UnknownError235** [comment]
> Can you try taking a lower res image, making sure it's the first thing in the timeline, and opening it? If it works, then swipe to the right 64MP image. If that works, then slowly continue swiping and gradually increase the speed.

It seems like make the issue appear less. Also the beta timeline makes it a bit better (the issue still appears when I open a old 64MP picture).

I also have no issue opening a remote 64MP image. 

> Also, which version of the A71 do you have? There is the 4G, 5G and 5G UW that have different specs.

I have the 4G model

**Comment by mertalev** [comment]
Does the `Bad state: Stream has been disposed.` error happen whenever this crash occurs? Does that error only happen when it crashes like this?

**Comment by UnknownError235** [comment]
Okay sorry, it seems like that error does not appear consistently, so probably does not have anything to do with my problem
