### ISSUE TITLE
v1.139.2 Docker Container Restart Loop

### ISSUE THREAD

**Issue by allancoding** [immich-app/immich#21189]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

When I upgraded from v1.138.1 to v1.139.2 the docker container infinity restarts. Downgrading to version v1.139.1 fixes the issue.

<img width="299" height="601" alt="Image" src="https://github.com/user-attachments/assets/041a2383-c7bf-4aae-a641-aa4432ec3af1" />

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.139.2

### Version of Immich Mobile App

v1.139.2

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ${UPLOAD_LOCATION}:/data
      - /mnt/Wilcken:/mnt/wilcken
      - /mnt/Gudmundson:/mnt/gudmundson
      - /mnt/Niles:/mnt/niles
      - /mnt/Public:/mnt/public
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: unless-stopped
    healthcheck:
      disable: false
    labels:
      - "com.centurylinklabs.watchtower.monitor-only=true"

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - immich-model-cache:/cache
    env_file:
      - stack.env
    restart: unless-stopped
    healthcheck:
      disable: false
    labels:
      - "com.centurylinklabs.watchtower.monitor-only=true"

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    volumes:
      - immich-redis:/data
    labels:
      - "com.centurylinklabs.watchtower.monitor-only=true"

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data

    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.monitor-only=true"

volumes:
  immich-model-cache:
  immich-redis:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/home/allan/immich/library
DB_DATA_LOCATION=/home/allan/immich/postgres
IMMICH_VERSION=release
DB_PASSWORD=***redacted***
DB_USERNAME=immich
DB_DATABASE_NAME=
IMMICH_PROCESS_INVALID_IMAGES=true
```

### Reproduction steps

1. docker compose up and the `immich-server`  with restart infinity
2. Check the logs

### Relevant log output

```shell
Initializing Immich v1.139.2
Detected CPU Cores: 4
Initializing Immich v1.139.2
Detected CPU Cores: 4
Initializing Immich v1.139.2
Detected CPU Cores: 4
Initializing Immich v1.139.2
Detected CPU Cores: 4
Initializing Immich v1.139.2
Detected CPU Cores: 4
Initializing Immich v1.139.2
Detected CPU Cores: 4
Initializing Immich v1.139.2
Detected CPU Cores: 4
Initializing Immich v1.139.2
Detected CPU Cores: 4
Initializing Immich v1.139.2
Detected CPU Cores: 4
Initializing Immich v1.139.2
Detected CPU Cores: 4
Initializing Immich v1.139.2
Detected CPU Cores: 4
Initializing Immich v1.139.2
Detected CPU Cores: 4
Initializing Immich v1.139.2
Detected CPU Cores: 4
```

### Additional information

Going back a version, the server starts up normally.

**Comment by alextran1502** [comment]
How much RAM do you have allocated for this?

**Comment by thomasss02** [comment]
Same here. I have Raspberry pi 4 with 8gb RAM. It crash after initialization. Docker container has Unlimited RAM use. 

Edit: After downgrading to 1.138.1 and then upgrading to v1.139.2 It works.

**Comment by thomasss02** [comment]
Perhaps unrelated
![_immich_server_logs (3).txt](https://github.com/user-attachments/files/21950826/_immich_server_logs.3.txt)

**Comment by xshyne** [comment]
I have the same issue after restarting the server, the new photos i added didn't have thumbnail. I started the job to generate the thumbnail generation and i got this issue of infinite restart. 
I got the issue only with photo took from my phone, with screenshot it seems to work normally (the thumbnail is generated correctly).

**Comment by allancoding** [comment]
> How much RAM do you have allocated for this?

16GB on the server. 12GB free

**Comment by irfanhakim-as** [comment]
Facing the same issue, I thought related to 'corrupted images' bcos images failed to generate thumbnail.. but I don't think that's the 'actual' cause since almost all images I've uploaded since then have all failed to generate thumbnail (when they're really not corrupt at all), and the container keeps restarting when attempting to generate a thumbnail for them.

The server itself is fine, resource usage is very, very free as it's been before.

More of my reports/logs are on this issue: https://github.com/immich-app/immich/issues/16044#issuecomment-3217182144

---

Update: can confirm that downgrading to the previous version, `v1.138.1`, solves the issue completely.

**Comment by schuettecarsten** [comment]
I had the same issue. For me it was related by assets that cannot be converted/processed by thumbnail generator causing a crash of the whole docker image.

**Comment by allancoding** [comment]
Updating to v1.139.3 solved the issue for me.

**Comment by skatsubo** [comment]
@irfanhakim-as @schuettecarsten @xshyne Could you share an image that triggers the issue?

Probably caused by https://github.com/immich-app/base-images/pull/259 and we'd like to see if the most recent libheif fixes it or do we need to rollback.

**Comment by irfanhakim-as** [comment]
It was happening to me consistently on version `v1.139.2@sha256:6bd954809e2ddd0e5557b3a57031255f88b1b1b20e90f4354c5c5bffca91d9af` (assuming this was what you were asking, its image tag). The issue's gone since downgrading back to `v1.138.1@sha256:ec0bb170125d404c8965a90fba0a1f654927e36423585bcc1ff8625211d4a9be`.

**Comment by allancoding** [comment]
> It was happening to me consistently on version `v1.139.2@sha256:6bd954809e2ddd0e5557b3a57031255f88b1b1b20e90f4354c5c5bffca91d9af` (assuming this was what you were asking, its image tag). The issue's gone since downgrading back to `v1.138.1@sha256:ec0bb170125d404c8965a90fba0a1f654927e36423585bcc1ff8625211d4a9be`.

Same here.

**Comment by skatsubo** [comment]
@irfanhakim-as Ah, sorry, I meant sharing the photo. If the issue is triggered by thumbnail generation for a particular image.

**Comment by cabaucom376** [comment]
I’m not sure what’s happening here, but v1.139.2 is the first version of immich I’ve used, and it’s a completely fresh installation. I linked my iPhone, backed up all my photos, and then went to the web interface to discover that I couldn’t see anything. I then figured out about thumbnail generation and went into the jobs section to start it. It only has one job active, and it never changes. Eventually, the container starts boot looping. v1.139.3 has not changed this for me. v1.138.1 at least allows me to select each photo manually and refresh the thumbnail but the job doesn't work. In fact it seems a lot of the jobs are just stuck and never changing with no clear way on how to stop them.

**Comment by irfanhakim-as** [comment]
@skatsubo After upgrading to said problematic version, the issue started happening to most newer images that were uploaded to the server - they were consistent too, as in, after trashing and permanently deleting the image and reuploading them, the same issue occurs. As I use an iPhone, the photos were mostly HEIC images I capture, or PNG images I screenshot.

I couldn't share the HEIC images bcos of the metadata attached to them, but I can share the PNG screenshot: https://bunkr.site/f/8yLXDvTE0FB7K

Just to clarify again, these photos no longer had any issue having their thumbnails generated/not crashing the server after downgrading. It's possible as @allancoding has mentioned, that it might also have been fixed in the latest `v1.139.3` version but I haven't tested.

**Comment by allancoding** [comment]
> Just to clarify again, these photos no longer had any issue having their thumbnails generated/not crashing the server after downgrading. It's possible as [@allancoding](https://github.com/allancoding) has mentioned, that it might also have been fixed in the latest `v1.139.3` version but I haven't tested.

With version `v1.139.2` I could not access the web interface because it was not even starting up. Downgrading to `v1.138.1` it would run normally. For me I don't think it was a thumbnail issue because it would have restarted later in the startup process. And yes version `v1.139.3` works like normal.

**Comment by xshyne** [comment]
@skatsubo [](url)

One of the image with the issue :  
![Image](https://github.com/user-attachments/assets/4a8c2ab0-760d-4ed4-809e-d30e3a65b102)

I just updated to 1.139.3 and the issue still happen.

**Comment by skatsubo** [comment]
Hey folks, could you post your hardware info?

- `uname -a`
- whether it's Raspberry Pi / which model (We saw several similar RPI-related issues recently)

Also what is the exit code in `docker inspect immich_server`?
- `docker inspect -f '{{ .State.ExitCode }}' immich_server`

**Comment by allancoding** [comment]
`Linux allan-server 6.1.0-37-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.140-1 (2025-05-22) x86_64 GNU/Linux`
Not a raspberrypi

**Comment by xshyne** [comment]
`Linux loki 6.6.39-v8+ #1783 SMP PREEMPT Thu Jul 11 18:56:16 BST 2024 aarch64 GNU/Linux`
i'm on a `Raspberry Pi 4 Model B Rev 1.4`

In `docker compose logs -f` i have : `immich_server exited with code 132`
In `docker inspect immich_server` i have : 
```
{
    "Start": "2025-08-25T22:23:05.700845522+02:00",
    "End": "2025-08-25T22:23:13.304272213+02:00",
    "ExitCode": 137,
    "Output": ""
},
```

**Comment by cabaucom376** [comment]
uname: `Linux ServerPI 6.12.27-v8+ #1876 SMP PREEMPT Tue May  6 15:12:28 BST 2025 aarch64 GNU/Linux`
model: `Raspberry Pi 4 Model B Rev 1.4`

There appears to be no boot looping issue in version 1.139.4 for me. However, sometimes thumbnail generation gets stuck in a perpetual active state and continues indefinitely until I manually stop and remove the containers, which then allows me to trigger thumbnail generation. It would be beneficial to have a way to forcefully stop or reset the jobs whenever they get stuck in an error state. At least for me, the problems related to thumbnail generation and boot looping seem to have been resolved in the latest release.

**Comment by irfanhakim-as** [comment]
> Hey folks, could you post your hardware info?
> 
>     * `uname -a`

`Linux 5a1de445ee7d 6.12.25+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.12.25-1+rpt1 (2025-04-30) aarch64 GNU/Linux` (on the Docker container)
 
>     * whether it's Raspberry Pi / which model (We saw several similar RPI-related issues recently)

Raspberry Pi 4 Model B, 8GB RAM.

> Also what is the exit code in `docker inspect immich_server`?
> 
>     * `docker inspect -f '{{ .State.ExitCode }}' immich_server`

`0`, atm, since no crashes on the downgraded version. These were part of my logs tho, I believe, when it was crashing previously: https://github.com/immich-app/immich/issues/16044#issuecomment-3217654669 (you could see at the end that it rebooted)

**Comment by aydarik** [comment]
> Hey folks, could you post your hardware info?
- `Linux raspberrypi 6.6.29-v8+ #1760 SMP PREEMPT Mon Apr 29 14:42:16 BST 2024 aarch64 GNU/Linux`
- `Raspberry Pi 4B 8GB`

> Also what is the exit code in docker inspect immich_server?
- `132`

**Comment by aydarik** [comment]
Maybe it's also worth mentioning that the server enters a crash loop whenever a thumbnail generation job is running. When the job is paused, the server runs without issues.

**Comment by irfanhakim-as** [comment]
> Maybe it's also worth mentioning that the server enters a crash loop whenever a thumbnail generation job is running. When the job is paused, the server runs without issues.

This seems to be my observation too when I was facing this issue

**Comment by schuettecarsten** [comment]
v1.139.4 crashes whenever I try to regenerate a thumbnail.
The container restarts without any useful message in docker logs.

```
Linux raspberrypi 6.12.34+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.12.34-1+rpt1~bookworm (2025-06-26) aarch64 GNU/Linux
Raspberry Pi 4B 8GB
```

**Comment by skatsubo** [comment]
To identify which images cause thumb gen to stuck / crash:

The thumbnail generation jobs are persisted in Redis. There is asset id in Redis records. To view them:
- either add bullmq Redis UI, such as Bull-board (docker image by deadly0, venatum and so on)
- or from command line smth like https://github.com/immich-app/immich/discussions/20548#discussioncomment-14052954

**Comment by aydarik** [comment]
I’ll share the [workaround](https://github.com/immich-app/immich/issues/21237#issuecomment-3227172633) here as well, since it seems to be related:

> If that works, you can add `VIPS_NOVECTOR=1` to Immich env variables and see if it helps with thumbnail generation in Immich.
>
> Related: https://github.com/libvips/libvips/issues/4647

**Comment by Marx314** [comment]
The workaround work perfectly.
I've also split the workers to troubleshoot it as the log were useless even in verbose for this case: https://immich.app/docs/administration/jobs-workers/
The split have the benefice of keeping the service up even if the jobs are failing <3

**Comment by skatsubo** [comment]
> split the workers
> The split have the benefice of keeping the service up even if the jobs are failing <3

Clever trick!

**Comment by skatsubo** [comment]
Eventually this will be fixed
- either by switching Immich base docker image to Debian Trixie - https://github.com/libvips/libvips/issues/4647#issuecomment-3228910097
- or when the highway fix propagates into libvips and Immich - https://github.com/google/highway/issues/2689

For now we have a workaround: adding `VIPS_NOVECTOR=1` to Immich env variables.

So I'm going to close the issue in favor of https://github.com/immich-app/immich/issues/21237.
