### ISSUE TITLE
Immich app not showing all pictures

### ISSUE THREAD

**Issue by andrzej-r** [immich-app/immich#23057]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

There are a number of similar issues, e.g. #17645, but the description that is best matching my experience is: https://www.reddit.com/r/immich/comments/1dev1ym/immich_app_not_showing_all_pictures/

After some time, usually several weeks after installation, Android Immich app starts missing some of the photos in the monitored directories. They are not shown in the Photos section at all, and therefore cannot be uploaded/backed up on the server. Uninstalling/reinstalling the app fixes the issue for another several weeks.

The issue is difficult to notice when it first occurs. Most of the photos appear in Photos as expected and only a small number of random photos is missing.

### The OS that Immich Server is running on

Debian (LXC on Proxmox)

### Version of Immich Server

v1.142.1

### Version of Immich Mobile App

v2.1.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Device make and model

Samsung M31

### Your docker-compose.yml content

```YAML
version: "3.8"
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: unless-stopped
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - ./model-cache:/cache
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    #image: redis:6.2-alpine@sha256:c5a607fb6e1bb15d32bbcf14db22787d19e428d59e31a5da67511b49bb0f1ccc
    image: docker.io/valkey/valkey:8-bookworm@sha256:fea8b3e67b15729d4bb70589eb03367bab9ad1ee89c876f54327fc7c6e618571
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping || exit 1

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:c44be5f2871c59362966d71eab4268170eb6f5653c0e6170184e72b38ffdf107
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    shm_size: 128mb
    restart: unless-stopped
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/storage/photos

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=***

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis

IMMICH_SERVER_URL=https://***
```

### Reproduction steps

* I'm importing photos from my camera to my android phone (the specific application I use is OI.Share by Olympus/OM System, it saves photos in /SD card/DCIM/OMDS)
* I open Immich, and I can see the imported images in Photos section, ready to upload.
  * At this stage I do not yet realise several random images are not showing up in this section
* I upload all new (available) images to the server, put them in the albums etc.
* Some time later I realise (by accident) a few images I expected to see were not uploaded to the Immich server.
  * I inspect the above import directory with a file browser - the missing images are in there together with all the successfully uploaded images.
  * I inspect the list of photos in the Android Immich app - it is missing some random photos
* Updating the app to the newest version (currently 2.1.0 build.3022) does not resolve the issue.
* Uninstalling and installing the app again fixes the issue - missing photos are now shown in the Photos section and can be uploaded to the Immich server. Immich app seems to work reliably.
* The issue re-occurs a few weeks later. Once it misses some photos the issue starts occurring every time I import/upload photos (but still affecting only a small and random subset of all photos).

### Relevant log output

```shell

```

**Comment by alextran1502** [comment]
Can you help me confirm if you go to App Settings > Sync Status > Press on Local Sync button and see if those pop up?

**Comment by WhiteWoodenWall** [comment]
I also had this issue on Google Pixel 7 Pro, and running a local sync caused them to appear in the Immich timeline.

Images taken around the same time were already visible though, so I'm not sure what caused it to miss the images that it did.

**Comment by bo0tzz** [comment]
Please make sure your server is up to date.

**Comment by thomasss02** [comment]
I'm experiencing this, too. After pressing Sync Local I see all the assets in timeline

**Comment by andrzej-r** [comment]
I've previously reinstalled the Immich app, which fixed the issue. So, pressing Local Sync now does nothing (green check mark before and after pressing it). I will try that solution when I see the issue next time, thanks.

I will of course update the server but when it happen before updating the server made no difference, so I went straight for a solution that worked previously (reinstalling the app).

**Comment by duongel** [comment]
I am experiencing the same problem. Not all photos in my folder that I have selected to upload to the Immich server from my Z Fold 7 are visible in the Immich mobile app. 

Reinstallation resolves the issue, but it reoccurs at random intervals after. I can verify that pressing local sync in settings resolves the issue, as newly added photos become visible. 

However, the upload process occasionally becomes stuck after new photos are visible. Resolving this issue by killing the mobile app from task manager is working so far. I noticed pressing sync with server in settings also triggers upload of new photos.

Immich is otherwise working great! Setting up the server with Nginx Proxy Manager and a Cloudflare tunnel to ensure global, family-wide access has been a massive improvement to my everyday life. Photos are now genuinely valuable - not just inaccessible files on an external drive to be forgotten.  
The ability to quickly search and share photos of old memories in real-time has made our conversations richer. Thank you for developing such a powerful, and basically free, tool for everyone! 🙏🙏🙏

-------------
Server: Ubuntu Server 24.04 running on MacBook Pro 2014 i7, 16GB RAM, Immich storage on external 2TB SSD
Server version: 2.1.0
App version: 2.1.0 build.3022

**Comment by SuBra98** [comment]
Experiencing the same on ios as well. All latest versions running for both immich and ios.

More details: I add photos to album, after album is synced in Immich mobile App I hide the photos in ios photos app. next time i run immich i need to run local sync to show the thumbnails for only these photos in immich.

**Comment by MawdleCode** [comment]
+1 for same problem.  I can take a string of photos and only 95% of them will appear in Immich.  Restarting the app or the phone has no effect.  Taking a new photo will (or may not) add to the app, but those ones missed never pop up unless I manually go and run the Local sync.

**Comment by jmgevers99** [comment]
+1 same problem here, immich and google photos do not line up anymore

**Comment by danielpanaite** [comment]
Same here on android, I can only see the new photos from the local album if I manually run the local sync job

**Comment by Shlokp** [comment]
Same issue on android, it's difficult to notice when photos start dropping off on the app. It's happened a few times but haven't managed to notice a pattern to help figure out the issue but seems to be more than a one off issue. Sometimes it's a random photo missing from a group of photos taken very close together.

Browsing through the old Reddit threads suggested logging in and out as a solution which works and missed photos instantly show up on the app and start backing up. 

Will try the local sync button next time I notice pictures missing.

Latest server and app version - 2.1
Android 16
Pixel 9 Pro XL

**Comment by headtr1ck** [comment]
I have the same issue on Android running 2.1.
The pictures are missing also from the local Camera album in immich.
Manually running the sync local job fixes it momentarily.

**Comment by jmgevers99** [comment]
Did this fix make it onto the 2.2 release?

Right now I can't fully trust immich because of this issue.

**Comment by mpu3000** [comment]
I am still experiencing the same issue even after updating - for me, even clicking on the local sync button does nothing, I only managed to see all the pictures once after deleting the SQLite database, but after that, the app crashed, signed me out, and after another sign-in, the missing pictures are still not visible (and/or uploading to the server).

**Comment by MawdleCode** [comment]
Issue still occurs on latest versions.  @alextran1502 - Please reopen this issue.

**Comment by bo0tzz** [comment]
@RocketRammer the fix was merged but not yet released.

**Comment by MawdleCode** [comment]
Issue should still be open then.. it's not complete.

**Comment by bo0tzz** [comment]
The PR that fixes it has been merged, so from our perspective it's complete.

**Comment by jmgevers99** [comment]
Issue still happens to me on the latest version unfortunately(2.3.1 server, 2.3.0 android)

**Comment by duongel** [comment]
Same here,
Android version 2.3.1
Server version 2.3.1

**Comment by alextran1502** [comment]
@duongel would the photo show up when you kill and cold start the app, instead of resuming it from the background?

**Comment by duongel** [comment]
Kind of, only on second opening.

Steps to reproduce:
- Immich runs in background or not (does not seem to matter), 
- add photo to sync folder, open Immich, new photo not showing up in Immich, 
- remove Immich from task switcher, open Immich again, new photo shows up

Android version 2.3.1 (Samsung Z Fold 7)
Server version 2.3.1

**Comment by jmgevers99** [comment]
@alextran1502 Could you please reopen this issue? Would be great if it could be fixed :)

**Comment by awonglk** [comment]
This is not fixed yet. I am noticing photos not showing up on "new timeline" even after running local sync. The missing photos are showing on the web interface. So clearly there is something different about how Android mobile app syncs the photos from the server.

**Comment by asterycs** [comment]
Hi, I just ran into what I think is this exact issue as well.

I noticed that some pictures that I took during the day wouldn't show up in the Immich timeline even though they showed up in gphotos and the native Photos app.

In the Immich app I noticed that the missing photos only show up in the "Latest" folder, not in any other folder such as "Recently saved", "Portraits", or "Live Photos". I checked carefully multiple times, both new and old timeline and after trying local sync from the settings.
I recently disabled the sync of the "Latest" folder (might be called something else in English) to avoid having all random photos from all messaging apps uploaded to my server. I kept all other relevant folders, but none of them seem to include the missing pictures except for the "Latest" folder.

Could it be that ios puts these pictures in an "uncategorized" folder or similar, that is ignored by the Immich app?

iphone 13, ios 26.2, Immich app version 2.4.1. I realize now that this issue is for Android, please let me know if I should open a new one.

**Comment by alextran1502** [comment]
@awonglk Are you still facing the issue?

@asterycs the "Recents" album includes all the photos on your device. "Recently Saved", "Portraits" and "Live Photos" are part of smart albums on iOS.

You can use the "Recents" album to upload, then double-tap on albums from messeging app to exclude them from being sync to the server

**Comment by awonglk** [comment]
@alextran1502 Yes this is still an issue for me on my Android client. The photos are showing in the web interface fine.

**Comment by alextran1502** [comment]
@awonglk, do you mind sending in the mobile app logs?

**Comment by awonglk** [comment]
@alextran1502 
Here you go..

[Immich_log_2026-01-20T091614.031248.log](https://github.com/user-attachments/files/24725692/Immich_log_2026-01-20T091614.031248.log)

Let me know if there's specifics you need from me

**Comment by alextran1502** [comment]
@awonglk Looks like the mobile app cannot communicate with the server/domain to perform a sync

```
Error in runInIsolateGentle  for remote-sync | ClientException with SocketException: Failed host lookup: 'immich2.whereisant.com' (OS Error: No address associated with hostname, errno = 7), uri=https://immich2.whereisant.com/api/sync/stream |
```

or 

```
2026-01-15 16:17:32.404621 | severe   | IsolateLogger        | Error in runInIsolateGentle  for remote-sync | ApiException 502: Failed to get sync stream: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.29.4</center>
</body>
</html>
 |
#0      SyncApiRepository.streamChanges (package:immich_mobile/infrastructure/repositories/sync_api.repository.dart:85)
<asynchronous suspension>
#1      SyncStreamService.sync (package:immich_mobile/domain/services/sync_stream.service.dart:49)
<asynchronous suspension>
#2      runInIsolateGentle.<anonymous closure>.<anonymous closure> (package:immich_mobile/utils/isolate.dart:58)
<asynchronous suspension>
#3      runInIsolateGentle.<anonymous closure> (package:immich_mobile/utils/isolate.dart:37)
<asynchronous suspension>
#4      WorkerImpl._anotherIsolate.<anonymous closure> (package:worker_manager/src/worker/worker_io.dart:106)
```

This indicates issue with your reverse proxy settings or DNS

**Comment by awonglk** [comment]
Hi Alex, could that be a transient error? There's many other "Starting hashing of assets" that have gone through without that error. 
I do occassionally restart my Immich server, causing that "502 Bad Gateway" error

**Comment by vekexasia** [comment]
Just found out this. Still happening to me I have the latest immich srv and app

**Comment by deajan** [comment]
Report for the sake of sanity:

I've had similar issues where android app wouldn't show any items from server, whearas on any computer it would work flawlessly.
I finally found my culprit: the phones prefer using IPv6 whereas other devices prefer IPv4.
Since the immich server was reachable via IPv4 but not via IPv6, I got the exact symptoms where everything would work except on android app.

**Comment by jmgevers99** [comment]
I unfortunately still have this problem basically every time I open immich after taking pictures.

Workload will be as follows:
1. Take loads of pictures
2. Wait some time (until I open immich again)
3. Open immich
4. Go to the backup screen
5. See X amount remaing (for instance 100)
6. Wait 10-15 seconds on the backup screen
7. 100 remaining suddenly jumps to 125 remaining.

It looks like the fix where it syncs local upon app startup works, but I would argue it should do that during a background job.

Other than that it seems that my immich also just doesn't really want to upload pictures when the app is not open. Ive experimented with having immich 'keep open' and closing the app from memory but in both cases it doesn't backup unless the app is open.

**Comment by sargo** [comment]
Android automatically revokes permissions for apps you rarely use. Unfortunately, the Immich app doesn't check permissions at startup, so it won't load or sync new photos. The permission prompt appears after logging in, so log out and log back in. Then go to Settings > Apps > Immich > Permissions and toggle off "Remove permissions if app is unused" to avoid the problem in the future.

**Comment by marcvorwerk** [comment]
> Android automatically revokes permissions for apps you rarely use. Unfortunately, the Immich app doesn't check permissions at startup, so it won't load or sync new photos. The permission prompt appears after logging in, so log out and log back in. Then go to Settings > Apps > Immich > Permissions and toggle off "Remove permissions if app is unused" to avoid the problem in the future.

Thank you, this was a very helpful hint!

I had the same issue: the Immich Android App no longer saw local photos. After the latest Android update, the storage/photos permission had been removed.
