### ISSUE TITLE
[Web] MEMORY LEAK - New version popup multiplying in background

### ISSUE THREAD

**Issue by Cedric-Boucher** [immich-app/immich#24079]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

When a new version of Immich comes out, the administrator account gets a popup on the web that tells them that there is a new version. However, it seems that a new popup gets added (on top of any existing ones) at some time interval... I had my computer sitting idle with a couple of Immich tabs open for a few days. When I came back, I found that my Immich browser tabs were using over 30GB of RAM, and there was clearly hundreds or more of the new version popup window on top of each other (the background was completely black).

### The OS that Immich Server is running on

TrueNas Scale 25.10 (irrelevant)

### Version of Immich Server

v2.3.1

### Version of Immich Mobile App

v2.3.1 (irrelevant)

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Device make and model

Firefox browser in Windows 10, if it matters

### Your docker-compose.yml content

```YAML
Default for TrueNas Scale
```

### Your .env content

```Shell
Default for TrueNas Scale
```

### Reproduction steps

1. Open a browser tab with the immich server
2. Wait until there is a new version of immich server
3. Leave the tab open and the computer on for a week or two
4. Hope your computer doesn´t crash from being out of memory

### Relevant log output

```shell

```

**Comment by bo0tzz** [comment]
Is this still happening on v2.3.1?

**Comment by Cedric-Boucher** [comment]
@bo0tzz well I can´t find out until a new version comes out :p

**Comment by Cedric-Boucher** [comment]
The latest version I can guarantee it was happening on is v2.2.3. If it was fixed for 2.3.0 or 2.3.1 then I was just not aware.

**Comment by Cedric-Boucher** [comment]
ah, was it fixed in v2.3.1 with #24013?

**Comment by bo0tzz** [comment]
It should, yes

**Comment by Cedric-Boucher** [comment]
ok, my bad then. You can close this issue. If it happens on v2.3.1 (when a new update comes out) I will create a new issue, but that shouldn´t be the case.

**Comment by ph1go** [comment]
I'm on 2.3.1 and this is still happening. I have about 3 seconds to achieve anything before the whole webui hangs for 15+ seconds.

Edit - to be a bit more helpful, v2.3.1 running on Docker (on Ubuntu)

Edit edit - after some time to reflect, v2.3.1 seems to be fine.

**Comment by zatricky** [comment]
@ph1go I put up a workaround `userscript` in a comment I wasn't able to find ... so I put it up in a [public gist](https://gist.github.com/zatricky/f6798c548129d37eb5fe7f2b68a74e92).

If you're on 2.3.1 though you should probably make a new issue or find an issue (for the current version) that isn't closed already.
