### ISSUE TITLE
[BUG] <title> Suddenly incorrect email or password

### ISSUE THREAD

**Issue by jwefers** [immich-app/immich#5907]
### The bug

After update to 1.91.4, i cannot log in with admin user and my personal user anymore (web). Second household user account still works. My android app with my personal user still seems to work (still active session?)

Bonus: Setting the admin password with `immich-admin reset-admin-password` does not fix it - still cannot use the just-set admin pw to log in

Note: I replaced the docker volumes with bind mounts - did the internal user for any component change?

### The OS that Immich Server is running on

Debian Bookworm

### Version of Immich Server

1.91.4

### Version of Immich Mobile App

1.91.4 build.116

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: unless-stopped

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.yml
      service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: unless-stopped

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - ${MACHINE_LEARNING_LOCATION}:/cache
    env_file:
      - .env
    restart: unless-stopped

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:b6124ab2e45cc332e16398022a411d7e37181f21ff7874835e0180f56a09e82a
    restart: unless-stopped

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${DATABASE_LOCATION}:/var/lib/postgresql/data
    restart: unless-stopped
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/ssdraid/immich/data
DATABASE_LOCATION=/ssdraid/immich/postgres
MACHINE_LEARNING_LOCATION=/ssdraid/immich/machine-learning

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=xxx
DB_PASSWORD=xxx

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Try to log in on web
2.
3.
...
```

**Comment by zackpollard** [comment]
Hey, we have had a couple of issues similar to this reported recently, would you be able to provide a dump of your database. Specifically the users table? I'm hoping we can replicate this ourselves with that data and figure out exactly what is going on.

**Comment by danieldietzler** [comment]
The easiest way to do that would probably be to join the Discord. Then you could DM us the dump

**Comment by jwefers** [comment]
sure, in a few hours, i'll provide it, thanks

**Comment by TwoD** [comment]
I'm having the same issue. Only have one user. Resetting the admin password does not help. Attempting to reset via the GUI in a browser which is still logged in just says "Unauthrorized".

Attachgin my users table contents.

[users.txt](https://github.com/immich-app/immich/files/13745009/users.txt)

**Comment by alextran1502** [comment]
You guys can follow the conversation here for a fix. 

https://discord.com/channels/979116623879368755/1185315110395322528

We currently don't understand why this issue happen yet

**Comment by TwoD** [comment]
Thanks, but I'd rather stick to using an actual issue tracker for issues, not an unorganized chat client.

**Comment by jwefers** [comment]
After some back and forth with Zack, the index is corrupted. After running psql `REINDEX users`, all works again.

I figured by doing some `EXPLAIN ANALYZE` on the queries for a user with a working and non-working user. It shows that the non-working users were not contained in the index.

**Comment by jwefers** [comment]
so the question would be if on a recent update, you changed the schema in regards to indexes and maybe postgres does not automatically update/recreate changed indices?

**Comment by zackpollard** [comment]
Hey @VoVAllen, we just wanted to loop you in on this issue to understand if pgvecto.rs could in any way cause something like this. Here's what we know so far:

- The index of our users (login) table somehow becomes corrupt, specifically the email field
- This happened during the upgrade to the new version
- We have had multiple reports of this issue since the latest upgrade which includes the change to use pgvecto.rs
- We haven't made any changes or run any SQL migrations around the users table
- We are not sure if this is isolated to the users index, because it would be much harder to spot elsewhere
- The image that this use specifically migrated from was `postgres:14-alpine@sha256:6a0e35296341e676fe6bd8d236c72afffe2dfe3d7eb9c2405c0f3fc04500cd07`
- The specific image they migrated to was `tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee`

We are essentially just wondering if, from your knowledge of the pgvecto.rs codebase, is there any way that it could somehow cause corrupted indexes elsewhere in postgres? We've never had reports of this kind of thing prior to this upgrade but we have now had 4 seperate reports of the issue. If you could shed any light on this, it would be appreciated. Thanks!

**Comment by VoVAllen** [comment]
@zackpollard We're aware of some edge device with low kernel version may have errors, like https://github.com/tensorchord/pgvecto.rs/issues/202, and we're fixing it. For the corrupted index, we have only encountered this issue during plugin upgrades. However, we have only tested it on the cloud and our own computer, so it's possible to have edge cases on other devices. 

To reset the pgvecto.rs:
- Delete all files under pgdata/pg_vectors
- Restart postgres

This would not affect any of your data (including embedding) inside the postgres. Only the index part is dropped. Then I would expect everything at least works. 

The pgvecto.rs index itself is isolated from other indexes. It's totally independent

**Comment by zackpollard** [comment]
> @zackpollard We're aware of some edge device with low kernel version may have errors, like [tensorchord/pgvecto.rs#202](https://github.com/tensorchord/pgvecto.rs/issues/202), and we're fixing it. For the corrupted index, we have only encountered this issue during plugin upgrades. However, we have only tested it on the cloud and our own computer, so it's possible to have edge cases on other devices.
> 
> To reset the pgvecto.rs:
> 
>     * Delete all files under pgdata/pg_vectors
> 
>     * Restart postgres
> 
> 
> This would not affect any of your data (including embedding) inside the postgres. Only the index part is dropped. Then I would expect everything at least works.
> 
> The pgvecto.rs index itself is isolated from other indexes. It's totally independent

Yea, this is the weird thing. This is not a pgvecto.rs index, it's completely unrelated to that, however it's only started showing up after we started to move users to the pgvecto.rs image.

**Comment by VoVAllen** [comment]
@zackpollard I read the thread in Discord. Does it happen only on the admin account? Or some data is broken here? pgvecto.rs is just an index, that won't modify anything inside postgres. It just receive the change inside postgres, and applies it on its own index. And when query happens, it returns the related rows. Nothing inside postgres would be affected.

**Comment by jwefers** [comment]
not just admin accounts. 2/3 users for me. And yes, the email column is a btree index.

**Comment by zackpollard** [comment]
> @zackpollard I read the thread in Discord. Does it happen only on the admin account? Or some data is broken here? pgvecto.rs is just an index, that won't modify anything inside postgres. It just receive the change inside postgres, and applies it on its own index. And when query happens, it returns the related rows. Nothing inside postgres would be affected. Even for the embedding, pgvecto.rs would just store another copy. No modification happens for postgres

The data itself appears to be fine, it's the btree index that has been corrupted somehow. A REINDEX on the table fixes the problem, but we are wondering how that index got corrupted in the first place.

**Comment by bo0tzz** [comment]
Note that we're not being suspicious of pgvecto.rs, it's just the only potential lead we have so we thought we'd ask :) From your explanation it sounds very unlikely to me that pgvecto.rs is involved here.

**Comment by VoVAllen** [comment]
One possibility might be pg14's minor version? The image of pgvecto.rs is built on a different minor version than pervious one? Thus some incompatibility might be introduced here

**Comment by VoVAllen** [comment]
https://www.migops.com/blog/important-postgresql-14-update-to-avoid-silent-corruption-of-indexes/
Found some pg14 blogs saying that btree might be silently corrupted in early version

**Comment by zackpollard** [comment]
> https://www.migops.com/blog/important-postgresql-14-update-to-avoid-silent-corruption-of-indexes/ @zackpollard @bo0tzz Found some pg14 blogs saying that btree might be silently corrupted in early version

Thanks for looking into it, however I don't believe we have previously had Immich on 14.4, if we have it hasn't been for a long time. The version most people should be upgrading from would've been 14.8 we believe.

**Comment by TwoD** [comment]
Thanks, that did work for me, but the command was `REINDEX TABLE users`.

**Comment by bengelnatz** [comment]
without reading everything: I fixed this issue for me by setting a new email for my user directly in the DB. My old username had an underscore ('_') in it address but not sure if that was the cause

**Comment by mertalev** [comment]
[This](https://www.citusdata.com/blog/2020/12/12/dont-let-collation-versions-corrupt-your-postgresql-indexes/) seems very relevant. I think the default collation in the old and new docker image may be different. The old image is Alpine-based and uses musl, while the new image is Debian-based and uses glibc. A change in collation can silently corrupt B-tree indices.

**Comment by VoVAllen** [comment]
@mertalev This [slide](https://www.postgresql.eu/events/pgconfeu2022/sessions/session/4040/slides/337/Collations%20in%20PostgreSQL%20-%20The%20good,%20the%20bad%20and%20the%20ugly%20-%20Tobias%20Bussmann.pdf) mentioned breaking change in glibc 2.28 might be the cause. 

![image](https://github.com/immich-app/immich/assets/8686776/66a0536f-36b5-437c-8492-e3ec4f9cbd9b)

**Comment by ausshir** [comment]
Unless I was doing something wrong, running "REINDEX TABLE users" and even deleting "pgdata/pg_vectors" did not resolve the issue for me.

Luckily I was still authed in another session and could change the 'email' of the admin account. That allowed me to log in again.

**Comment by mertalev** [comment]
> @mertalev The breaking change in glibc 2.28 mentioned in this [slide](https://www.postgresql.eu/events/pgconfeu2022/sessions/session/4040/slides/337/Collations%20in%20PostgreSQL%20-%20The%20good,%20the%20bad%20and%20the%20ugly%20-%20Tobias%20Bussmann.pdf) might be the cause. 
> 
> 
> 
> ![image](https://github.com/immich-app/immich/assets/8686776/66a0536f-36b5-437c-8492-e3ec4f9cbd9b)
> 
> 

That seems likely. I think it'd be good to set the collation ourselves to make sure it's consistent.

**Comment by Igor01-Tech** [comment]
> After some back and forth with Zack, the index is corrupted. After running psql `REINDEX users`, all works again.
> 
> I identified this by doing some `EXPLAIN ANALYZE` on the queries for a user with a working and non-working user. It shows that the non-working users were not contained in the index on the email field.

Can you explain how to reindex users step by step? Tried to lo into running postgres container and doing

root@9fbc397237eb:/# REINDEX users
bash: REINDEX: command not found
root@9fbc397237eb:/# postgres REINDEX users
"root" execution of the PostgreSQL server is not permitted.
The server must be started under an unprivileged user ID to prevent
possible system security compromise.  See the documentation for
more information on how to properly start the server.

How can I reindex the users? I cant login with any of my two accounts anymore..

**Comment by Igor01-Tech** [comment]
> Unless I was doing something wrong, running `REINDEX TABLE users` and even deleting `pgdata/pg_vectors/*` did not resolve the issue for me.
> 
> Luckily I was still authed in another session and could change the 'email' of the admin account. That allowed me to log in again.

Wow, that did the trick for all my users (1 admin, 1 user) Thanks!

**Comment by JoePassanante** [comment]
For folks looking for a quick command, this fixed the issue for me on my Rasp Pi 4s. 

Docker: 
`docker exec -it immich_postgres psql -U postgres -d immich -c "REINDEX TABLE users;"`

Specifically 
`docker exec -it immich_postgres psql -U <postgres user name used in .env>-d <postgres database for immich> -c "REINDEX TABLE users;"`

**Comment by dlang123** [comment]
I tried the `REINDEX users`.. didn't work for me, then I tried to change the email with an already logged in session as someone else suggested.  That also didn't seem to work. I thought, maybe I really do just have my password screwed up, so then I tried to run the `immich-admin reset-admin-password`

I was spammed with the following errors in the logs, restarting Immich continues spamming the following errors.  Immich is back up and appears to be running, but with the following errors repeatedly spammed to the log.


Error: connect ECONNREFUSED 192.168.10.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.10.100',
  port: 6379
}

**Comment by raudette** [comment]
If it helps at all, this issue impacted 2/2 users for me, and REINDEX TABLE USERS; on the DB solved the issue.

**Comment by psilantropy** [comment]
Completed a 1.93.3 to 1.95.1 update and only admin user locked out.
Above command resolved. Thank you.
