### ISSUE TITLE
[BUG] Background upload doesn't work even with Automatic Foreground Backup and Automatic background backup service enabled.

### ISSUE THREAD

**Issue by gumpdy** [immich-app/immich#5994]
### The bug

Background upload doesn't work even with Automatic Foreground Backup and Automatic background backup service enabled. Android app battery management is set to Unrestricted.

### The OS that Immich Server is running on

Android

### Version of Immich Server

1.91.4

### Version of Immich Mobile App

1.91.4 build.116

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
I don't know how to see that using the unRAID GUI, but the problem seems exclusive to the Android app functionality anyway
```

### Your .env content

```Shell
I don't know how to see that using the unRAID GUI, but the problem seems exclusive to the Android app functionality anyway
```

### Reproduction steps

```bash
1.Open app, click on backup icon, see it begin uploading the video file. wait for a few percent to progress
2. take app away from foreground OR close it entirely
3. open app again, click on backup icon, see it start all over again.
```

### Additional information

I also occasionaly see the percentage counter flicker between higher and lower percentage values, almost like it's showing the percentage values for duplicate asynchronous upload streams

**Comment by gdamx** [comment]
Same issue for me however it forgets the albums that are selected and it disables the foreground and background backup

**Comment by gumpdy** [comment]
> Same issue for me however it forgets the albums that are selected and it disables the foreground and background backup

Make sure your app-specific battery optimization is aet to unrestricted on stock android. If you have a manufacturer's bloatware, refer to this guide: https://dontkillmyapp.com/

**Comment by gdamx** [comment]
I've done already still same issue. Photos seem to backup but videos don't . And by the time I check the app it forgets the backup location

**Comment by gdamx** [comment]
![Screenshot_20231226_224310](https://github.com/immich-app/immich/assets/99370593/30cf6e28-8103-4752-afa8-25cf54f26c13)


Literally just left screen on to backup a video , nothing backed up assets remaining is the same

**Comment by aisbergde** [comment]
I also have seen lost selected folders to upload. Not sure, if they have been really lost, or if they just didn't display. But I added them again. I will see, if they will be forgotten again.

**Comment by gdamx** [comment]
They keep forgetting for me

**Comment by eagerto-learn** [comment]
I have the same issue. It forgets the albums selected and disables the foreground and background backup. After I reselect the albums and leave the upload screen on, it tries to upload some videos that I already uploaded from a couple months before. After each "try" is finished the remaining video number stays the same and it tries another video from even an earlier time. 

Already set the battery to unrestricted, still same issue everytime I open the app.

**Comment by gumpdy** [comment]
For myself, when I first open the app, no albums are shown as selected but seemingly after some initialization, appear as expected. I suggest one of you open another bug issue.

**Comment by nkgiovannivl** [comment]
I have same issue, but if I starts the app enter to cloud icon nothing it's show, press back an again enter to cloud icon, all info appers.

But, it's seems something strange with the videos, beacuse sync deamon/service sync all videos again and again until I allow Notifications for the app on my phone

**Comment by kic68** [comment]
Definitely the same issue for me, the (Android) app forgets which albums to upload when I actively close it. It does not save the albums to upload - so the foreground and background engines are correct when they stop to upload.

**Comment by Jebula999** [comment]
Any update on this?
Facing the same issue.

500+ images and video's all sotting in a never ending Queue because the app has ro be in the foreground and open in that specific menu in order for it to upload

**Comment by alextran1502** [comment]
@Jebula999 Are you using reverse proxy/dns/cloudflare? Do you mind try access your instance over local ip?

**Comment by Jebula999** [comment]
> @Jebula999 Are you using reverse proxy/dns/cloudflare? Do you mind try access your instance over local ip?

I am currently on the same local network as my server running Immich.

I am connected directly via the server local IP address

**Comment by alextran1502** [comment]
So it uploads fine when you open the app, just not working well on the background? Which phone model do you have?

**Comment by Jebula999** [comment]
Correct.

It's a Samsung S24 Ultra.

Note the file amount difference in the 2 images attached.

All I did was minimise Immich and open my browser to respond to this message

Unfortunately my clock it not in the image, but they were taken 8min apart.
As soon as I tabbed back to Immich it started uploading again.
![Screenshot_20240425_230312](https://github.com/immich-app/immich/assets/11380895/2b32b692-f2a6-4731-be18-78ea4a0bcd30)
![Screenshot_20240425_231119](https://github.com/immich-app/immich/assets/11380895/70a02fae-c82d-4b82-9414-00ac950a0626)

**Comment by Jebula999** [comment]
@alextran1502 Ok, then that makes more sense.
Thank you for the insight, have a good weekend :)

**Comment by kic68** [comment]
Good morning!
We should not mix up two issues here. One is the "normal" Android energy optimizing killing app issue. This can and should be fixed in the widely spread Android settings. 

The other issue is Immich related - as the App does NOT SAVE ITS CONFIGUATION before it is killed or closed. This seems to happen to some people including myself. 

Steps to reproduce:
- Configue Immich App
- Let it start uploading
- Do other things for a while or close the app
- Open the app again
- There's no configuration anymore, i.e. it does not know the server to sync with anymore.

In that case it will only ever start uploading again if you configure the settings again. Which doesn't help for long. It is definitely NOT related to energy settings, at least not more than these kills can trigger the deletion of Immich's configuration.

Also on a Samsung Galaxy S24 Ultra.

**Comment by alextran1502** [comment]
@kic68 I saw this reported sometimes, it is quite strange that it happens for some users but not all. Do you access the instance locally? How many assets do you have on your device?

**Comment by kic68** [comment]
Please don't laugh, about 60k photos and videos. Stopping uploading after a few hundred. So this would be a big pain to always reconfigure.

**Comment by alextran1502** [comment]
@kic68 With that amount of assets, I think it might have taken sometimes for the album to be read/sort/filter with already uploaded assets, so it is not necessarily forgot

**Comment by szmarczak** [comment]
This is a bug. I can reproduce this by trying to upload 1.6G video file on a 40Mbps upload speed. Even if I wait enough time in the background, it still fails to upload.

**Comment by misaligar** [comment]
Same for me. Background upload doesn't work.

**Comment by simone7121** [comment]
Hello everyone,

I encountered a similar issue while using Immich. After some troubleshooting, I realized that bypassing the Cloudflare proxy resolved the problem (for me), and everything started working as expected.

It seems that the proxy was causing some kind of interference, potentially blocking certain requests or adding unwanted latency. For anyone else experiencing this, temporarily bypassing Cloudflare might help isolate whether the proxy is the source of the issue.

Additionally, I have a NAT 2 Italian internet connection, and after performing a traceroute, I noticed that my Fritz!Box router was redirecting me directly to my local address. (Even if i'm behind a reerse proxy) This might also be related to the issue, as it could interfere with how traffic is routed through Cloudflare.

It might be worth investigating if there are specific configurations needed for Immich to work smoothly with Cloudflare in proxied mode, or if certain headers are being stripped or blocked, or if the TTL is limited—I'm not sure.

**Comment by mmomjian** [comment]
Duplicate/tracked in #2567
