### ISSUE TITLE
[BUG] (android) new images do not show until status of the Server is known

### ISSUE THREAD

**Issue by Moosbee** [immich-app/immich#6422]
### The bug

New Images will not appear in the Galary(when starting the App), until the status of the Server is known, this can in certain cases be very long, to long.

### The OS that Immich Server is running on

Truenas scale

### Version of Immich Server

v1.91.4

### Version of Immich Mobile App

v1.91.4

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
unknown, use the Community train application
```

### Your .env content

```Shell
unknown, use the Community train application
```

### Reproduction steps

```bash
1. have a Server running in the local network
2. connect your phone to it
3. it should work
4. close the app
5. shut down server or change Lan&Wifi
6. Take a photo, without the App activ
7. oben the App
8. **The new Image will not appear as long as the App is trying to connect to the Server**
9. If you turn the Internet off, the App will go offline, the Image appears.
...
```

**Comment by vide** [comment]
This seems to be still the case with 1.118.2, and it's pretty easy to verify if you have the Immich server behind a VPN connection, and open the app without the VPN connected.

If one of the goals of Immich is replace the G app, this is something that should be fixed, because I really love the Immich Android app and I want to use it as my main & only gallery app, but I have to fallback to the other one when I cannot connect to my VPN or the phone is in flight mode.

**Comment by sanzinluka** [comment]
As of today, on version 1.123.0 on a Pixel 9 Pro this bug is still present. 
If I take a photo on airplane mode it doesn't show in the gallery, but as soon as I turn on mobile connectivity the picture pops up.

**Comment by dirixmjm** [comment]
As of today, on version 1.124.0 build.173 Samsung A52 this bug is still present.
I'd rather not expose the immich server to the internet, but also would prefer a single picture gallary app.

**Comment by Sprk-nl** [comment]
The 1.124.0 build.173 on Samsung Galaxy S22 also has the bug present.

**Comment by zymbiosis** [comment]
Is there a way to add a bounty onto this particular issue or show monetary support?  I would love to show my support towards finishing up this particular issue.  Thanks!

**Comment by vahidtvj** [comment]
For me, new images don't appear at all when the internet is off. However, tapping the little cloud button, then opening the "Select Backup Albums" page, and immediately going back makes the new images appear.

Device: Redmi Note 13 Pro 5G
OS: Android 14 (HyperOS)
Mobile App Version: v1.126.1 (Build 184)

Steps to Reproduce:
- Take a new photo while offline
- Open Immich (new photo doesn’t appear) 
- Tap the cloud button → tap the "Select" button on "Backup Albums" card → Go back
- New photo appears.

**Comment by DanielBCoffaro** [comment]
The same for me exists on pixel 7 pro.

**Comment by vahidtvj** [comment]
> For me, new images don't appear at all when the internet is off. However, tapping the little cloud button, then opening the "Select Backup Albums" page, and immediately going back makes the new images appear.
> 
> Device: Redmi Note 13 Pro 5G OS: Android 14 (HyperOS) Mobile App Version: v1.126.1 (Build 184)
> 
> Steps to Reproduce:
> 
>     * Take a new photo while offline
> 
>     * Open Immich (new photo doesn’t appear)
> 
>     * Tap the cloud button → tap the "Select" button on "Backup Albums" card → Go back
> 
>     * New photo appears.

Works fine for me in the new version. New images appear after about 7 seconds of opening the app.
Mobile App Version: v1.135.1 (Build 202)

**Comment by alextran1502** [comment]
fixed with the new timeline implementation
