### ISSUE TITLE
Videos with "Date acquired" before 1970 show up in the future

### ISSUE THREAD

**Issue by svezina** [immich-app/immich#7935]
### The bug

Hi folks,
I've been trying to get old scanned pictures and old digitized videos to work with Immich. Photos work fine for dates before 1970 thanks to EXIF data.

But for videos, if I put for example 1958-01-01 as the "Date acquired", it ends up in 2036 in Immich.

Not a big deal since pre-1970 videos are pretty rare.
Thanks

### The OS that Immich Server is running on

PopOS 22.04

### Version of Immich Server

1.98.2

### Version of Immich Mobile App

n/a

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: '3.8'

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#


services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - ${EXTERNAL_PATH}:/usr/src/app/external
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: ['start.sh', 'microservices']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - ${EXTERNAL_PATH}:/usr/src/app/external
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
EXTERNAL_PATH=/home/user/immich-photos
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
- Change an MP4's Date Acquired to a date before 1970-01-01 (using BulkFileChanger or other)
- Upload to Immich.
```

**Comment by alextran1502** [comment]
darn it, we really didn't accounted for file that are before 1970 which is 0 in Unix time

**Comment by AshkanArabim** [comment]
not sure how difficult it is, but isn't this solved by simply using 64-bit unix time instead of 32-bit?

**Comment by yantramai** [comment]
I would like to take a stab at it, let his be my "good first issue"

**Comment by jrasm91** [comment]
I don't think this is an immich bug. We definitely support dates in the past. Either this was an exiftool-vendored bug (that has since been fixed) or your metadata is incorrectly set. I'm pretty sure exif date format is `yyyy:mm:dd hh:mm:ss`.

![image](https://github.com/user-attachments/assets/ead175fb-d305-46a9-8ee3-6d96fe23c116)

**Comment by jrasm91** [comment]
BTW - I believe this issue was opened before immich supported editing the datetime directly. It might be easier to just upload the original file again, and then use the edit feature to change the day/time.

**Comment by svezina** [comment]
Hi folks,
I just tried on v1.114.0. The issue persists.

I created a small video file and used BulkFileChanger to put a couple of its dates to Janurary 1, 1940. The 3 dates I changed are:
Media Files - Item Date
Media Files - Date encoded
Media Files - Date acquired

After upload to Immich, the date becomes 2006-01-01.
Here is the video file, hoping the metadata survives Github's upload : 

https://github.com/user-attachments/assets/42dc13bc-cc40-4500-8890-16680fc30912

**Comment by jrasm91** [comment]
Why don't you zip the file and upload it and then I can take another look.

**Comment by svezina** [comment]
Good idea, here it is.
[datetest2.zip](https://github.com/user-attachments/files/16972038/datetest2.zip)

**Comment by jrasm91** [comment]
The values in exif are 2308. I am guessing the way you used the tool to change the date was incorrect.

![image](https://github.com/user-attachments/assets/31219b92-4063-455f-b6a8-608ef88a6f66)

**Comment by jrasm91** [comment]
FWIW - We keep a list of tag names that we look for dates in. The list is:
- SubSecDateTimeOriginal
- DateTimeOriginal
- SubSecCreateDate
- CreationDate
- CreateDate
- SubSecMediaCreateDate
- MediaCreateDate
- DateTimeCreated

MP4 videos usually container `CreateDate`. This video specifically has a value of `2006:01:01 23:24:02` which is being used in Immich. We don't consider the `Date Acquired` (I had never heard of it before this issue)
