### ISSUE TITLE
High CPU usage starting at 00:00 when external Library is not available since around v1.100.x

### ISSUE THREAD

**Issue by kladderadeng** [immich-app/immich#9263]
### The bug

I can not pin down the exact build, but I think it started with version 1.100.0.
Every night, starting at 00:00, immich_microservices starts to consume 100% CPU of one core and redis-server starts to consume about 50% of a core of my server. This is how it looks the next morning when looking at htop:
![image](https://github.com/immich-app/immich/assets/111387593/cc9de0f2-1c19-4de5-8759-9a042a1440d8)

Checking the output of docker compose logs, I can see this:
![immich_high_cpu_usage_2](https://github.com/immich-app/immich/assets/111387593/066ff570-9a3d-4f08-a3a3-715897bed821)

And in my monitoring I can see clearly that it all started at 00:00:
![image](https://github.com/immich-app/immich/assets/111387593/5e2e3094-57f2-416d-b3e6-1c856651611a)

I assume this has something to do with my external library. That one sits on a NAS that shuts down every night at 23:30 and can stay off for days. I know this is not optimal for immich, but I made sure that all processes in immich (automatic rescan of librarys and what not) are off. Also, this was not an issue before version 1.100.x.
I have seen that there is an automatic library rescan job in immich that starts at 00:00, but I made sure that it is still off after updating to version 1.100.x. Currently I do not see any configuration or job that starts at 00:00.
I am pretty sure it has something to do with my external library being offline, but I can not figure out (also by reading through the changelogs) what could have changed in that regard to cause this issue.

Before 1.100.x, it was no problem shutting down the NAS. Immich was still running fine and users were able to upload their photos, without immich and redis consuming so much CPU cycles.

### The OS that Immich Server is running on

Ubuntu Server 22.04.4 LT

### Version of Immich Server

v1.103.1

### Version of Immich Mobile App

n/a

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /media/nas/Pictures:/media/nas/Pictures:ro
    env_file:
      - .env
    #ports:
      #- 2283:3001
    depends_on:
      - redis
      - database
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.publish=lan"
      - "traefik.http.routers.immich.entrypoints=https"
      - "traefik.http.routers.immich.rule=Host(`immich.example.com`)"
      - "traefik.http.routers.immich.tls=true"
      - "traefik.http.routers.immich.tls.certresolver=letsencrypt"
      - "traefik.http.routers.immich.middlewares=default@file"
      - "traefik.http.routers.immich.service=immich"
      - "traefik.http.services.immich.loadbalancer.server.port=3001"
      - "traefik.docker.network=docker_trusted"
    networks:
      - docker_trusted

  immich-microservices:
    container_name: immich-microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    extends:
      file: hwaccel.yml
      service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /opt/immich/reverse-geocoding-dump:/usr/src/app/.reverse-geocoding-dump
      - /media/nas/Pictures:/media/nas/Pictures:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - docker_trusted

  immich-machine-learning:
    container_name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    volumes:
      - /opt/immich/ml-cache:/cache
    env_file:
      - .env
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - docker_trusted

  redis:
    container_name: immich-redis
    image: redis:6.2-alpine@sha256:60e49e22fa5706cd8df7d5e0bc50ee9bab7c608039fa653c4d961014237cca46
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - docker_trusted

  database:
    container_name: immich-postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - /opt/immich/pgdata:/var/lib/postgresql/data
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - docker_trusted

  backup:
    container_name: immich-db-dumper
    image: prodrigestivill/postgres-backup-local
    restart: unless-stopped
    user: 70:1000
    env_file:
      - .env
    environment:
      POSTGRES_HOST: ${DB_HOSTNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      SCHEDULE: "30 23 0 * * *"
      BACKUP_NUM_KEEP: 7
      BACKUP_DIR: /db_dumps
      TZ: "Europe/Berlin"
    volumes:
      - /opt/immich/db_dumps:/db_dumps
    depends_on:
      - database
    networks:
      - docker_trusted

networks:
  docker_trusted:
    name: docker_trusted
    external: true
```

### Your .env content

```Shell
UPLOAD_LOCATION=/opt/immich/library
IMMICH_VERSION=release
TYPESENSE_API_KEY=***redacted***
DB_PASSWORD=***redacted***

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich-postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich-redis

# Self-Defined
TZ=Europe/Berlin
PUID=1000
PGID=1000
```

### Reproduction steps

```bash
1. NAS with external Library is on
2. Start immich stack
3. Shut NAS with external Library off
4. At 00:00 CPU utilization will go up to 100% for immich_microservices and to 50% for redis-server.
```

**Comment by danieldietzler** [comment]
Sharing more immich server logs, and especially immich microservices logs, both at around 12:00am, would be much appreciated! :)

**Comment by jrasm91** [comment]
I believe this issue has been resolved.

**Comment by kladderadeng** [comment]
Thanks for the heads up @jrasm91 and sorry @danieldietzler for not responding. Somehow the E-Mail notification of your post slipped through :-(

I tried again with the latest build and it is still the same issue. I suppose what you are referring to @jrasm91 is the change in the latest version regarding a lost database connection, that is then attempted to re-establish again once it was lost? In my case I am sure it has nothing to do with the database connection, since the database is always Online and hosted in the same stack as the immich services. What I can see however is, that as soon as the external Library on my NAS is not available anymore, the CPU usage starts to go up until it is maxed out and this is when I come back to the server the next morning, all fans are crying for mercy ;-)

Here we can see as CPU usage ramps up slowly after 23:30 (that is when the NAS where the pictures aka my external library is stored shuts down):
![image](https://github.com/user-attachments/assets/64d3955f-5ed9-43fb-bc46-3757068c7526)


And these are the processes consuming CPU power:
![image](https://github.com/user-attachments/assets/a14a5841-13ef-4c20-ab52-477fb2f994ab)


Regarding the logs @danieldietzler, do you mean the output of docker compose logs or logs from within the container? I can not see currently that I volume-mount a directory that contains logfiles at the moment.

**Comment by danieldietzler** [comment]
Immich writes the logs to stdout, so `docker compose logs` should give you them

**Comment by kladderadeng** [comment]
@flavien26 Unfortunately no. There was something mentioned a few versions ago that this should be fixed, but even with the recent versions I have the same issue. This is also the reason I am not using Immich at the moment.
