### ISSUE TITLE
Panasonic S5 IIx RW2 Raws show as pink noise

### ISSUE THREAD

**Issue by t3dc** [immich-app/immich#9336]
### The bug

As discussed and described [here](chore/imagemagick-7.1.1-24), RW2 raw files shot on a Panasonic S5 IIx show up as pink noise.

![Screenshot 2024-05-08 at 10 00 07 AM](https://github.com/immich-app/immich/assets/52919338/cc51ba12-b733-4243-86ea-d8961fb53b8e)

### The OS that Immich Server is running on

Debian 12.4 (aarch 64 / RPi 5)

### Version of Immich Server

v1.103.1

### Version of Immich Mobile App

v1.103.0 build 155

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:b6124ab2e45cc332e16398022a411d7e37181f21ff7874835e0180f56a09e82a
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
#UPLOAD_LOCATION=/media/ted/disk 5
UPLOAD_LOCATION=./storage

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=****

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Take lovely pictures using the Panasonic S5 IIx
2. Review them and determine they weren't as good as you thought
3. Upload the .RW2 Raw Files to Immich
4. Try to look at them in Immich
```

### Additional information

May need a bit of coaching on the logs, but happy to provide.  I assume I should monitor a log while uploading an RW2, but which docker container should I be watching? Where does ingest/thumbnail gen happen?

Thanks!

**Comment by mertalev** [comment]
> May need a bit of coaching on the logs, but happy to provide. I assume I should monitor a log while uploading an RW2, but which docker container should I be watching? Where does ingest/thumbnail gen happen?

The microservices container will have the relevant logs. But since it technically succeeds in generating a "preview", I'm afraid the logs won't be very interesting.

**Comment by Piston-Broke** [comment]
Same results here with Panasonic GH6

**Comment by jrasm91** [comment]
Can you retest these images again to see if the problem persists?

**Comment by mertalev** [comment]
This issue is from before we started using snapshots for libraw. DC-S5 MkII is listed as a supported camera in the snapshot, but not in the latest official release, so this issue is probably fixed.

**Comment by mertalev** [comment]
Same thing for DC-GH6.

**Comment by jrasm91** [comment]
I'm pretty sure there were other reports of pink previews that have been fixed as well, so closing.

**Comment by t3dc** [comment]
Late to the party, but also want to confirm all those ugly pink previews are gone. Thank you so much!

**Comment by palsol** [comment]
I have the same issue with Lumix S9 files. I’m using Immich from the TrueNAS App Store.

**The OS that Immich Server is running on**
truenas ElectricEel-24.10.0.2

**Version of Immich Server**
v1.126.1

**Comment by mertalev** [comment]
libraw doesn't currently [support](https://www.libraw.org/supported-cameras-202403) DC-S9 images.

**Comment by ColinZeb** [comment]
![Image](https://github.com/user-attachments/assets/33f2bf1d-80d1-4104-9a9d-2af0fbdfed4e)
v1.126.1 latest version Still have issue, model S5M2

**Comment by ColinZeb** [comment]
copy from this, https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
Just add one line for server

      - ${EXT_LOCATION}:/usr/src/app/external

**Comment by gearseekers** [comment]
The S5IIX and S5II issue still persists. I deployed from the docker compose provided on Ubuntu 24.04

**Comment by Charles-IX** [comment]
> Can you describe how you're deploying Immich? Is it the normal Docker Compose or is it a variant (Imagegenius, Nix, Arch, etc.)?

I am using the official Docker Compose method and can confirm that the issue persists.
All Raws show up as distorted pink noise.
Willing to provide any information if necessary.
