### ISSUE TITLE
Unable to play GIF on mobile

### ISSUE THREAD

**Issue by JVT038** [immich-app/immich#9628]
### The bug

When viewing a GIF on Android, it's just a single frame and it doesn't play.

### The OS that Immich Server is running on

DSM 7.2

### Version of Immich Server

v1.105.1

### Version of Immich Mobile App

v1.105.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

name: immich

networks:
  # caddy:
  #   external: true
  #   name: caddy_default
  traefik:
    external: true
    name: traefik_proxy

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    command: [ "start.sh", "immich" ]
    networks:
      - traefik
      - default
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - sockets:/sockets
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      ## HTTP Routers
      - traefik.http.routers.immich-rtr.rule=Host(`immich.$DOMAINNAME`)
      - traefik.http.routers.immich-rtr.entrypoints=https
      - traefik.http.routers.immich-rtr.tls=true
      - traefik.http.routers.immich-rtr.priority=10
      - traefik.http.routers.immich-rtr.service=immich-svc
      - traefik.http.routers.immich-rtr.middlewares=chain-basic@file
      - traefik.http.services.immich-svc.loadbalancer.server.port=3001

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:release
    command: [ "start.sh", "microservices" ]
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    networks:
      - default
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - sockets:/sockets
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always
    devices:
      - /dev/dri:/dev/dri

  immich-machine-learning:
    build:
      context: $DOCKERDIR/immich/immich-ml
      dockerfile: Dockerfile
    container_name: immich_machine_learning
    networks:
      - default
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - model-cache:/cache
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always
    networks:
      - default
    command: redis-server /etc/redis.conf
    volumes:
      - sockets:/sockets
      - $DOCKERDIR/immich/redis.conf:/etc/redis.conf
      - /etc/TZ:/etc/timezone:ro
      - $DOCKERDIR/immich/redisdb:/db

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    user: 1026:100
    command: postgres -c unix_socket_directories='/var/run/postgresql/,/sockets/'
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
      PGPORT: ${DB_PORT}
    volumes:
      - $DOCKERDIR/immich/pgdata:/var/lib/postgresql/data
      - sockets:/sockets
    restart: always

volumes:
  sockets:
    external: true
  model-cache:
```

### Your .env content

```Shell
DB_HOSTNAME=/sockets
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich
DB_PORT=5433
REDIS_PASSWORD="password"
REDIS_SOCKET=/sockets/immich_redis.sock
UPLOAD_LOCATION=$DOCKERDIR/immich/Gallerij
JWT_SECRET=secret
TYPESENSE_API_KEY=apikey
```

### Reproduction steps

```bash
1. Upload GIF
2. View GIF on mobile
3. See error
```

**Comment by Ador-able** [comment]
Same problem, want to add support

**Comment by Quenom** [comment]
Same issue on ios app

**Comment by Ador-able** [comment]
After checking, i found that in order to play the gif, we need to turn on loading the original image in the Settings

The gif can be played normally

I feel like we could use some refinement here

**Comment by Ador-able** [comment]
> After checking, i found that in order to play the gif, we need to turn on loading the original image in the Settings
> 
> The gif can be played normally
> 
> I feel like we could use some refinement here

After upgrading to v1.106.4, this method no longer works

**Comment by omeryagmurlu** [comment]
> > After checking, i found that in order to play the gif, we need to turn on loading the original image in the Settings
> > The gif can be played normally
> > I feel like we could use some refinement here
> 
> After upgrading to v1.106.4, this method no longer works

The problem is probably that the load original image functionality is broken. I noticed that the mobile app never loads the originals after last update

**Comment by ThiscketCrab** [comment]
Yep same issue here. Unraid server os. Newest immich versions. Newest android app versions.

**Comment by kyaustad** [comment]
Also having the issue on ipados

**Comment by cjdw94** [comment]
Sorry to necro, but just wanted to chime in that I do not have GIF playback on iOS, either.  Only in the web UI.

**Comment by AlphaCraft9658** [comment]
When accessing the online GIF from a mobile device that doesn't have it stored locally, the playback doesn't happen. Similarly, when Public-Immich-Proxy tries to pull a GIF, it also cannot play it back as a GIF. While the other project is not directly related to Immich, that issue might have the same or a similar cause, with Immich not giving the full GIF for playback when some kind of client, that is not the web client, is attempting to request the resource.

**Comment by Qrrbrbirlbel** [comment]
The same applies to GIFs in memories (on mobile). The GIF also doesn't play when viewed in memories on the web.

**Comment by planedrop** [comment]
Still haven't seen any updates on this, not the end of the world, but would be a nice feature to have. 

Is there any other thread related to the GIFs not playing? (in case I'm missing it and there has been updates, though I am still seeing this on 138).

**Comment by Danilado** [comment]
@planedrop They play if you turn on Load original image in Asset Viewer settings

**Comment by planedrop** [comment]
@Danilado they don't for me, enabled that and restarted the app but still not seeing any gifs be playable when opening them. 

I think someone above said that no longer works in the newer versions as well.

**Comment by Danilado** [comment]
@planedrop This was fixed in July 2024

How big are your gifs? I have a 65Mb gif and it takes like 30 seconds to load before it starts playing.

**Comment by planedrop** [comment]
@Danilado I have a rather small one at 350KiB and have had it open for about 1 minute and it hasn't started playing. 

I'll mess with a few more things but yeah pretty sure it's not working. Whereas they play instantly on the web client.

**Comment by jonvdveen** [comment]
❎ Issue still persistent on iOS.

**Comment by dboling19** [comment]
Issue still present on Android Mobile App v 2.1.0 build 5022

**Comment by spaceduck8** [comment]
Issue present on beta timeline on version 2.2.1 (build.5024). GIFs play when beta timeline is disabled.

**Comment by planedrop** [comment]
Just adding another "still present" comment here.

**Comment by Attila047** [comment]
The problem persists, and it’s particularly disruptive given the hardware capabilities of the M4 iPad Pro. You are essentially forced to choose between two compromised experiences:

• Option A: New Timeline OFF
• Pros: GIFs play normally within the app.
• Cons: Severe stuttering when browsing large albums containing high-resolution plain images.

• Option B: New Timeline ON
• Pros: Smooth, fluid browsing experience across large albums.
• Cons: GIFs fail to play natively; you are forced to use a web browser like Safari to view them.

**Comment by LanceTrahan** [comment]
Still present on Android (v2.3.0 Build 3027) with server v2.3.1

Photo is also local to my phone, so downloading to view shouldn't be the issue.

**Comment by dltmdcks98** [comment]
Still present on  server v2.4.1

**Comment by edm3di** [comment]
> The problem persists, and it’s particularly disruptive given the hardware capabilities of the M4 iPad Pro. You are essentially forced to choose between two compromised experiences:
> 
> • Option A: New Timeline OFF • Pros: GIFs play normally within the app. • Cons: Severe stuttering when browsing large albums containing high-resolution plain images.
> 
> • Option B: New Timeline ON • Pros: Smooth, fluid browsing experience across large albums. • Cons: GIFs fail to play natively; you are forced to use a web browser like Safari to view them.

This issue is currently due to New Timeline. Timeline ON GIFs don't play on mobile app (but they do via web browser). Timeline OFF plays natively on mobile app.

Android 2.4.1 build.3030

**Comment by Iapetus-11** [comment]
I am also having this issue on Android app version 2.5.6 build.3037

**Comment by spice-calc** [comment]
Same problem on Android app. Pretty sad about this.

**Comment by tbutz12** [comment]
Also experiencing this issue on new timeline.

**Comment by JVT038** [comment]
Damn, it took almost two years, but it's been closed! Thanks @LeLunZ for your hard work!

**Comment by cjdw94** [comment]
I tried to bring this up on Discord, but my server is updated to v3.0.1, my iOS app is v3.0.0, and GIFs still do not play.  They play about a frame, and then just stop.  This issue is not fixed.

When I commented on the issue a long time ago, that was before the beta timeline was introduced.  Ever since we’ve had the new timeline feature, GIFs have not worked for me at all.

**Comment by LeLunZ** [comment]
@cjdw94 could you please upload one of the gifs here that arent playing.

**Comment by HawaiianPizza** [comment]
@LeLunZ I'm not the person you're asking, but I have the same issue for Android. Here's a GIF that doesn't play for me:

<img width="480" height="304" alt="Image" src="https://github.com/user-attachments/assets/490c7d75-045b-4187-83bc-acdd228a75db" />

**Comment by LeLunZ** [comment]
@HawaiianPizza which android version are you on?

**Comment by CapSel** [comment]
Here is one on iPhone 17 Pro. Same bug with this image on OnePlus 15. Both have newest OS.
Both apps don't play this gif.
Web version of immich on Safari has same problem.
![image](https://github.com/user-attachments/assets/01852e20-0f0a-4d63-b265-cc7e6e62e37b)

**Comment by LeLunZ** [comment]
@HawaiianPizza @CapSel do both your gifs not play on the browser and in the app?
And do they show a GIF Badge on the thumbnail in the gallery (both mobile and browser)?
 
One possible reason gifs aren't playing is because immich thinks they don't have a duration. Could you rerun the metadata extraction job please and see if that changes anything?

if that doesn't work, please remove the gif from immich (also from trash), and reupload it and see if that changes anything.

**Comment by CapSel** [comment]
Re-uploading gif fixed issue for me on Safari, iOS app, Linux Firefox, Android app, Android Firefox.

**Comment by HawaiianPizza** [comment]
Rerunning the metadata extraction worked! Thank you!

**Comment by cjdw94** [comment]
I can also confirm that running the metadata extraction job fixed all of my older GIFs.  Newer GIFs worked immediately, before I ran the job.

(Possibly) A false alarm - but everyone should consider running metadata extraction if you have older GIFs in your library that aren’t playing on mobile (I’m on iOS and it worked for me).

Problem solved!  =D

**Comment by cjdw94** [comment]
> Re-uploading gif fixed issue for me on Safari, iOS app, Linux Firefox, Android app, Android Firefox.

This might be useful info for the devs.  Before I ran metadata extraction, a newly saved GIF **was** working.

Metadata extraction fixed all my older GIFs.
